/**
 * Portions of this module are modifications based on work created and shared by Google:
 *
 *   http://code.google.com/policies.html
 *
 * and used according to terms described in the Creative Commons 3.0 Attribution License:
 *
 *   http://creativecommons.org/licenses/by/3.0/
 *
 * Specifically, the gtfs-realtime.proto:
 *
 *   http://code.google.com/transit/realtime/docs/gtfs-realtime_proto.html
 *
 * was used to generate the classes contained within.
 *
 * Portions of this module are modifications based on work created by the New York
 * City Metropolitan Transportation Authority.
 *
 * All code is Copyright (C) 2011 Google, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *          http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/google/transit/realtime/gtfs-realtime-MNR.proto

package com.google.transit.realtime;

public final class GtfsRealtimeMNR {
  private GtfsRealtimeMNR() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(com.google.transit.realtime.GtfsRealtimeMNR.mnrStopTimeUpdate);
  }
  public interface MnrStopTimeUpdateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:transit_realtime.MnrStopTimeUpdate)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string track = 1;</code>
     *
     * <pre>
     *can add additional fields here without having to //extend StopTimeUpdate again
     * </pre>
     */
    boolean hasTrack();
    /**
     * <code>optional string track = 1;</code>
     *
     * <pre>
     *can add additional fields here without having to //extend StopTimeUpdate again
     * </pre>
     */
    java.lang.String getTrack();
    /**
     * <code>optional string track = 1;</code>
     *
     * <pre>
     *can add additional fields here without having to //extend StopTimeUpdate again
     * </pre>
     */
    com.google.protobuf.ByteString
        getTrackBytes();

    /**
     * <code>optional string trainStatus = 2;</code>
     */
    boolean hasTrainStatus();
    /**
     * <code>optional string trainStatus = 2;</code>
     */
    java.lang.String getTrainStatus();
    /**
     * <code>optional string trainStatus = 2;</code>
     */
    com.google.protobuf.ByteString
        getTrainStatusBytes();
  }
  /**
   * Protobuf type {@code transit_realtime.MnrStopTimeUpdate}
   */
  public static final class MnrStopTimeUpdate extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:transit_realtime.MnrStopTimeUpdate)
      MnrStopTimeUpdateOrBuilder {
    // Use MnrStopTimeUpdate.newBuilder() to construct.
    private MnrStopTimeUpdate(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MnrStopTimeUpdate(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MnrStopTimeUpdate defaultInstance;
    public static MnrStopTimeUpdate getDefaultInstance() {
      return defaultInstance;
    }

    public MnrStopTimeUpdate getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MnrStopTimeUpdate(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              track_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              trainStatus_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.transit.realtime.GtfsRealtimeMNR.internal_static_transit_realtime_MnrStopTimeUpdate_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.transit.realtime.GtfsRealtimeMNR.internal_static_transit_realtime_MnrStopTimeUpdate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.transit.realtime.GtfsRealtimeMNR.MnrStopTimeUpdate.class, com.google.transit.realtime.GtfsRealtimeMNR.MnrStopTimeUpdate.Builder.class);
    }

    public static com.google.protobuf.Parser<MnrStopTimeUpdate> PARSER =
        new com.google.protobuf.AbstractParser<MnrStopTimeUpdate>() {
      public MnrStopTimeUpdate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MnrStopTimeUpdate(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MnrStopTimeUpdate> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TRACK_FIELD_NUMBER = 1;
    private java.lang.Object track_;
    /**
     * <code>optional string track = 1;</code>
     *
     * <pre>
     *can add additional fields here without having to //extend StopTimeUpdate again
     * </pre>
     */
    public boolean hasTrack() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string track = 1;</code>
     *
     * <pre>
     *can add additional fields here without having to //extend StopTimeUpdate again
     * </pre>
     */
    public java.lang.String getTrack() {
      java.lang.Object ref = track_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          track_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string track = 1;</code>
     *
     * <pre>
     *can add additional fields here without having to //extend StopTimeUpdate again
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTrackBytes() {
      java.lang.Object ref = track_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        track_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRAINSTATUS_FIELD_NUMBER = 2;
    private java.lang.Object trainStatus_;
    /**
     * <code>optional string trainStatus = 2;</code>
     */
    public boolean hasTrainStatus() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string trainStatus = 2;</code>
     */
    public java.lang.String getTrainStatus() {
      java.lang.Object ref = trainStatus_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          trainStatus_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string trainStatus = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTrainStatusBytes() {
      java.lang.Object ref = trainStatus_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        trainStatus_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      track_ = "";
      trainStatus_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTrackBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTrainStatusBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTrackBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTrainStatusBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.google.transit.realtime.GtfsRealtimeMNR.MnrStopTimeUpdate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.transit.realtime.GtfsRealtimeMNR.MnrStopTimeUpdate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.transit.realtime.GtfsRealtimeMNR.MnrStopTimeUpdate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.transit.realtime.GtfsRealtimeMNR.MnrStopTimeUpdate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.transit.realtime.GtfsRealtimeMNR.MnrStopTimeUpdate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.transit.realtime.GtfsRealtimeMNR.MnrStopTimeUpdate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.google.transit.realtime.GtfsRealtimeMNR.MnrStopTimeUpdate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.google.transit.realtime.GtfsRealtimeMNR.MnrStopTimeUpdate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.google.transit.realtime.GtfsRealtimeMNR.MnrStopTimeUpdate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.transit.realtime.GtfsRealtimeMNR.MnrStopTimeUpdate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.transit.realtime.GtfsRealtimeMNR.MnrStopTimeUpdate prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code transit_realtime.MnrStopTimeUpdate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:transit_realtime.MnrStopTimeUpdate)
        com.google.transit.realtime.GtfsRealtimeMNR.MnrStopTimeUpdateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.transit.realtime.GtfsRealtimeMNR.internal_static_transit_realtime_MnrStopTimeUpdate_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.transit.realtime.GtfsRealtimeMNR.internal_static_transit_realtime_MnrStopTimeUpdate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.transit.realtime.GtfsRealtimeMNR.MnrStopTimeUpdate.class, com.google.transit.realtime.GtfsRealtimeMNR.MnrStopTimeUpdate.Builder.class);
      }

      // Construct using com.google.transit.realtime.GtfsRealtimeMNR.MnrStopTimeUpdate.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        track_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        trainStatus_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.transit.realtime.GtfsRealtimeMNR.internal_static_transit_realtime_MnrStopTimeUpdate_descriptor;
      }

      public com.google.transit.realtime.GtfsRealtimeMNR.MnrStopTimeUpdate getDefaultInstanceForType() {
        return com.google.transit.realtime.GtfsRealtimeMNR.MnrStopTimeUpdate.getDefaultInstance();
      }

      public com.google.transit.realtime.GtfsRealtimeMNR.MnrStopTimeUpdate build() {
        com.google.transit.realtime.GtfsRealtimeMNR.MnrStopTimeUpdate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.google.transit.realtime.GtfsRealtimeMNR.MnrStopTimeUpdate buildPartial() {
        com.google.transit.realtime.GtfsRealtimeMNR.MnrStopTimeUpdate result = new com.google.transit.realtime.GtfsRealtimeMNR.MnrStopTimeUpdate(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.track_ = track_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.trainStatus_ = trainStatus_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.transit.realtime.GtfsRealtimeMNR.MnrStopTimeUpdate) {
          return mergeFrom((com.google.transit.realtime.GtfsRealtimeMNR.MnrStopTimeUpdate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.transit.realtime.GtfsRealtimeMNR.MnrStopTimeUpdate other) {
        if (other == com.google.transit.realtime.GtfsRealtimeMNR.MnrStopTimeUpdate.getDefaultInstance()) return this;
        if (other.hasTrack()) {
          bitField0_ |= 0x00000001;
          track_ = other.track_;
          onChanged();
        }
        if (other.hasTrainStatus()) {
          bitField0_ |= 0x00000002;
          trainStatus_ = other.trainStatus_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.transit.realtime.GtfsRealtimeMNR.MnrStopTimeUpdate parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.transit.realtime.GtfsRealtimeMNR.MnrStopTimeUpdate) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object track_ = "";
      /**
       * <code>optional string track = 1;</code>
       *
       * <pre>
       *can add additional fields here without having to //extend StopTimeUpdate again
       * </pre>
       */
      public boolean hasTrack() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string track = 1;</code>
       *
       * <pre>
       *can add additional fields here without having to //extend StopTimeUpdate again
       * </pre>
       */
      public java.lang.String getTrack() {
        java.lang.Object ref = track_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            track_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string track = 1;</code>
       *
       * <pre>
       *can add additional fields here without having to //extend StopTimeUpdate again
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTrackBytes() {
        java.lang.Object ref = track_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          track_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string track = 1;</code>
       *
       * <pre>
       *can add additional fields here without having to //extend StopTimeUpdate again
       * </pre>
       */
      public Builder setTrack(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        track_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string track = 1;</code>
       *
       * <pre>
       *can add additional fields here without having to //extend StopTimeUpdate again
       * </pre>
       */
      public Builder clearTrack() {
        bitField0_ = (bitField0_ & ~0x00000001);
        track_ = getDefaultInstance().getTrack();
        onChanged();
        return this;
      }
      /**
       * <code>optional string track = 1;</code>
       *
       * <pre>
       *can add additional fields here without having to //extend StopTimeUpdate again
       * </pre>
       */
      public Builder setTrackBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        track_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object trainStatus_ = "";
      /**
       * <code>optional string trainStatus = 2;</code>
       */
      public boolean hasTrainStatus() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string trainStatus = 2;</code>
       */
      public java.lang.String getTrainStatus() {
        java.lang.Object ref = trainStatus_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            trainStatus_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string trainStatus = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTrainStatusBytes() {
        java.lang.Object ref = trainStatus_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          trainStatus_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string trainStatus = 2;</code>
       */
      public Builder setTrainStatus(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        trainStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string trainStatus = 2;</code>
       */
      public Builder clearTrainStatus() {
        bitField0_ = (bitField0_ & ~0x00000002);
        trainStatus_ = getDefaultInstance().getTrainStatus();
        onChanged();
        return this;
      }
      /**
       * <code>optional string trainStatus = 2;</code>
       */
      public Builder setTrainStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        trainStatus_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:transit_realtime.MnrStopTimeUpdate)
    }

    static {
      defaultInstance = new MnrStopTimeUpdate(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:transit_realtime.MnrStopTimeUpdate)
  }

  public static final int MNR_STOP_TIME_UPDATE_FIELD_NUMBER = 1005;
  /**
   * <code>extend .transit_realtime.TripUpdate.StopTimeUpdate { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.transit.realtime.GtfsRealtime.TripUpdate.StopTimeUpdate,
      com.google.transit.realtime.GtfsRealtimeMNR.MnrStopTimeUpdate> mnrStopTimeUpdate = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.transit.realtime.GtfsRealtimeMNR.MnrStopTimeUpdate.class,
        com.google.transit.realtime.GtfsRealtimeMNR.MnrStopTimeUpdate.getDefaultInstance());
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_MnrStopTimeUpdate_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_transit_realtime_MnrStopTimeUpdate_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n3com/google/transit/realtime/gtfs-realt" +
      "ime-MNR.proto\022\020transit_realtime\032/com/goo" +
      "gle/transit/realtime/gtfs-realtime.proto" +
      "\"7\n\021MnrStopTimeUpdate\022\r\n\005track\030\001 \001(\t\022\023\n\013" +
      "trainStatus\030\002 \001(\t:o\n\024mnr_stop_time_updat" +
      "e\022+.transit_realtime.TripUpdate.StopTime" +
      "Update\030\355\007 \001(\0132#.transit_realtime.MnrStop" +
      "TimeUpdateB\035\n\033com.google.transit.realtim" +
      "e"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.transit.realtime.GtfsRealtime.getDescriptor(),
        }, assigner);
    internal_static_transit_realtime_MnrStopTimeUpdate_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_transit_realtime_MnrStopTimeUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_transit_realtime_MnrStopTimeUpdate_descriptor,
        new java.lang.String[] { "Track", "TrainStatus", });
    mnrStopTimeUpdate.internalInit(descriptor.getExtensions().get(0));
    com.google.transit.realtime.GtfsRealtime.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
