// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/google/transit/realtime/gtfs-realtime-MTARR.proto

package com.google.transit.realtime;

public final class GtfsRealtimeMTARR {
  private GtfsRealtimeMTARR() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(com.google.transit.realtime.GtfsRealtimeMTARR.mtaRailroadStopTimeUpdate);
    registry.add(com.google.transit.realtime.GtfsRealtimeMTARR.mtaRailroadCarriageDetails);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MtaRailroadStopTimeUpdateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:transit_realtime.MtaRailroadStopTimeUpdate)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string track = 1;</code>
     */
    boolean hasTrack();
    /**
     * <code>optional string track = 1;</code>
     */
    java.lang.String getTrack();
    /**
     * <code>optional string track = 1;</code>
     */
    com.google.protobuf.ByteString
        getTrackBytes();

    /**
     * <code>optional string trainStatus = 2;</code>
     */
    boolean hasTrainStatus();
    /**
     * <code>optional string trainStatus = 2;</code>
     */
    java.lang.String getTrainStatus();
    /**
     * <code>optional string trainStatus = 2;</code>
     */
    com.google.protobuf.ByteString
        getTrainStatusBytes();
  }
  /**
   * Protobuf type {@code transit_realtime.MtaRailroadStopTimeUpdate}
   */
  public  static final class MtaRailroadStopTimeUpdate extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:transit_realtime.MtaRailroadStopTimeUpdate)
      MtaRailroadStopTimeUpdateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MtaRailroadStopTimeUpdate.newBuilder() to construct.
    private MtaRailroadStopTimeUpdate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MtaRailroadStopTimeUpdate() {
      track_ = "";
      trainStatus_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MtaRailroadStopTimeUpdate(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              track_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              trainStatus_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.transit.realtime.GtfsRealtimeMTARR.internal_static_transit_realtime_MtaRailroadStopTimeUpdate_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.transit.realtime.GtfsRealtimeMTARR.internal_static_transit_realtime_MtaRailroadStopTimeUpdate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadStopTimeUpdate.class, com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadStopTimeUpdate.Builder.class);
    }

    private int bitField0_;
    public static final int TRACK_FIELD_NUMBER = 1;
    private volatile java.lang.Object track_;
    /**
     * <code>optional string track = 1;</code>
     */
    public boolean hasTrack() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string track = 1;</code>
     */
    public java.lang.String getTrack() {
      java.lang.Object ref = track_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          track_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string track = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTrackBytes() {
      java.lang.Object ref = track_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        track_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRAINSTATUS_FIELD_NUMBER = 2;
    private volatile java.lang.Object trainStatus_;
    /**
     * <code>optional string trainStatus = 2;</code>
     */
    public boolean hasTrainStatus() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string trainStatus = 2;</code>
     */
    public java.lang.String getTrainStatus() {
      java.lang.Object ref = trainStatus_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          trainStatus_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string trainStatus = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTrainStatusBytes() {
      java.lang.Object ref = trainStatus_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        trainStatus_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, track_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, trainStatus_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, track_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, trainStatus_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadStopTimeUpdate)) {
        return super.equals(obj);
      }
      com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadStopTimeUpdate other = (com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadStopTimeUpdate) obj;

      boolean result = true;
      result = result && (hasTrack() == other.hasTrack());
      if (hasTrack()) {
        result = result && getTrack()
            .equals(other.getTrack());
      }
      result = result && (hasTrainStatus() == other.hasTrainStatus());
      if (hasTrainStatus()) {
        result = result && getTrainStatus()
            .equals(other.getTrainStatus());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTrack()) {
        hash = (37 * hash) + TRACK_FIELD_NUMBER;
        hash = (53 * hash) + getTrack().hashCode();
      }
      if (hasTrainStatus()) {
        hash = (37 * hash) + TRAINSTATUS_FIELD_NUMBER;
        hash = (53 * hash) + getTrainStatus().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadStopTimeUpdate parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadStopTimeUpdate parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadStopTimeUpdate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadStopTimeUpdate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadStopTimeUpdate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadStopTimeUpdate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadStopTimeUpdate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadStopTimeUpdate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadStopTimeUpdate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadStopTimeUpdate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadStopTimeUpdate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadStopTimeUpdate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadStopTimeUpdate prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code transit_realtime.MtaRailroadStopTimeUpdate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:transit_realtime.MtaRailroadStopTimeUpdate)
        com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadStopTimeUpdateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.transit.realtime.GtfsRealtimeMTARR.internal_static_transit_realtime_MtaRailroadStopTimeUpdate_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.transit.realtime.GtfsRealtimeMTARR.internal_static_transit_realtime_MtaRailroadStopTimeUpdate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadStopTimeUpdate.class, com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadStopTimeUpdate.Builder.class);
      }

      // Construct using com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadStopTimeUpdate.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        track_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        trainStatus_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.transit.realtime.GtfsRealtimeMTARR.internal_static_transit_realtime_MtaRailroadStopTimeUpdate_descriptor;
      }

      @java.lang.Override
      public com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadStopTimeUpdate getDefaultInstanceForType() {
        return com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadStopTimeUpdate.getDefaultInstance();
      }

      @java.lang.Override
      public com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadStopTimeUpdate build() {
        com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadStopTimeUpdate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadStopTimeUpdate buildPartial() {
        com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadStopTimeUpdate result = new com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadStopTimeUpdate(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.track_ = track_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.trainStatus_ = trainStatus_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadStopTimeUpdate) {
          return mergeFrom((com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadStopTimeUpdate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadStopTimeUpdate other) {
        if (other == com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadStopTimeUpdate.getDefaultInstance()) return this;
        if (other.hasTrack()) {
          bitField0_ |= 0x00000001;
          track_ = other.track_;
          onChanged();
        }
        if (other.hasTrainStatus()) {
          bitField0_ |= 0x00000002;
          trainStatus_ = other.trainStatus_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadStopTimeUpdate parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadStopTimeUpdate) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object track_ = "";
      /**
       * <code>optional string track = 1;</code>
       */
      public boolean hasTrack() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string track = 1;</code>
       */
      public java.lang.String getTrack() {
        java.lang.Object ref = track_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            track_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string track = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTrackBytes() {
        java.lang.Object ref = track_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          track_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string track = 1;</code>
       */
      public Builder setTrack(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        track_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string track = 1;</code>
       */
      public Builder clearTrack() {
        bitField0_ = (bitField0_ & ~0x00000001);
        track_ = getDefaultInstance().getTrack();
        onChanged();
        return this;
      }
      /**
       * <code>optional string track = 1;</code>
       */
      public Builder setTrackBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        track_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object trainStatus_ = "";
      /**
       * <code>optional string trainStatus = 2;</code>
       */
      public boolean hasTrainStatus() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string trainStatus = 2;</code>
       */
      public java.lang.String getTrainStatus() {
        java.lang.Object ref = trainStatus_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            trainStatus_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string trainStatus = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTrainStatusBytes() {
        java.lang.Object ref = trainStatus_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          trainStatus_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string trainStatus = 2;</code>
       */
      public Builder setTrainStatus(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        trainStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string trainStatus = 2;</code>
       */
      public Builder clearTrainStatus() {
        bitField0_ = (bitField0_ & ~0x00000002);
        trainStatus_ = getDefaultInstance().getTrainStatus();
        onChanged();
        return this;
      }
      /**
       * <code>optional string trainStatus = 2;</code>
       */
      public Builder setTrainStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        trainStatus_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:transit_realtime.MtaRailroadStopTimeUpdate)
    }

    // @@protoc_insertion_point(class_scope:transit_realtime.MtaRailroadStopTimeUpdate)
    private static final com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadStopTimeUpdate DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadStopTimeUpdate();
    }

    public static com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadStopTimeUpdate getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<MtaRailroadStopTimeUpdate>
        PARSER = new com.google.protobuf.AbstractParser<MtaRailroadStopTimeUpdate>() {
      @java.lang.Override
      public MtaRailroadStopTimeUpdate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MtaRailroadStopTimeUpdate(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MtaRailroadStopTimeUpdate> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MtaRailroadStopTimeUpdate> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadStopTimeUpdate getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MtaRailroadCarriageDetailsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:transit_realtime.MtaRailroadCarriageDetails)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *Indicates the number of bikes permitted per carriage.
     *0=bikes prohibited, -1=No limit.
     * </pre>
     *
     * <code>optional int32 bicycles_allowed = 1 [default = 0];</code>
     */
    boolean hasBicyclesAllowed();
    /**
     * <pre>
     *Indicates the number of bikes permitted per carriage.
     *0=bikes prohibited, -1=No limit.
     * </pre>
     *
     * <code>optional int32 bicycles_allowed = 1 [default = 0];</code>
     */
    int getBicyclesAllowed();

    /**
     * <pre>
     *A description of the carriage type/model.
     * </pre>
     *
     * <code>optional string carriage_class = 2;</code>
     */
    boolean hasCarriageClass();
    /**
     * <pre>
     *A description of the carriage type/model.
     * </pre>
     *
     * <code>optional string carriage_class = 2;</code>
     */
    java.lang.String getCarriageClass();
    /**
     * <pre>
     *A description of the carriage type/model.
     * </pre>
     *
     * <code>optional string carriage_class = 2;</code>
     */
    com.google.protobuf.ByteString
        getCarriageClassBytes();

    /**
     * <code>optional .transit_realtime.MtaRailroadCarriageDetails.QuietCarriage quiet_carriage = 3 [default = UNKNOWN_QUIET_CARRIAGE];</code>
     */
    boolean hasQuietCarriage();
    /**
     * <code>optional .transit_realtime.MtaRailroadCarriageDetails.QuietCarriage quiet_carriage = 3 [default = UNKNOWN_QUIET_CARRIAGE];</code>
     */
    com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails.QuietCarriage getQuietCarriage();

    /**
     * <code>optional .transit_realtime.MtaRailroadCarriageDetails.ToiletFacilities toilet_facilities = 4 [default = UNKNOWN_TOILET_FACILITIES];</code>
     */
    boolean hasToiletFacilities();
    /**
     * <code>optional .transit_realtime.MtaRailroadCarriageDetails.ToiletFacilities toilet_facilities = 4 [default = UNKNOWN_TOILET_FACILITIES];</code>
     */
    com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails.ToiletFacilities getToiletFacilities();
  }
  /**
   * Protobuf type {@code transit_realtime.MtaRailroadCarriageDetails}
   */
  public  static final class MtaRailroadCarriageDetails extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:transit_realtime.MtaRailroadCarriageDetails)
      MtaRailroadCarriageDetailsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MtaRailroadCarriageDetails.newBuilder() to construct.
    private MtaRailroadCarriageDetails(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MtaRailroadCarriageDetails() {
      bicyclesAllowed_ = 0;
      carriageClass_ = "";
      quietCarriage_ = 0;
      toiletFacilities_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MtaRailroadCarriageDetails(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              bicyclesAllowed_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              carriageClass_ = bs;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails.QuietCarriage value = com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails.QuietCarriage.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                quietCarriage_ = rawValue;
              }
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails.ToiletFacilities value = com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails.ToiletFacilities.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                toiletFacilities_ = rawValue;
              }
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.transit.realtime.GtfsRealtimeMTARR.internal_static_transit_realtime_MtaRailroadCarriageDetails_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.transit.realtime.GtfsRealtimeMTARR.internal_static_transit_realtime_MtaRailroadCarriageDetails_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails.class, com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails.Builder.class);
    }

    /**
     * <pre>
     * Whether the carriage has toilet facilities onboard.
     * </pre>
     *
     * Protobuf enum {@code transit_realtime.MtaRailroadCarriageDetails.QuietCarriage}
     */
    public enum QuietCarriage
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * It is unknown if the carriage is designated as a quiet carriage.
       *  This is the default case.
       * </pre>
       *
       * <code>UNKNOWN_QUIET_CARRIAGE = 0;</code>
       */
      UNKNOWN_QUIET_CARRIAGE(0),
      /**
       * <pre>
       * The carriage is designated a quiet carriage.
       * </pre>
       *
       * <code>QUIET_CARRIAGE = 1;</code>
       */
      QUIET_CARRIAGE(1),
      /**
       * <pre>
       * The carriage is not designated as a quiet carriage.
       * </pre>
       *
       * <code>NOT_QUIET_CARRIAGE = 2;</code>
       */
      NOT_QUIET_CARRIAGE(2),
      ;

      /**
       * <pre>
       * It is unknown if the carriage is designated as a quiet carriage.
       *  This is the default case.
       * </pre>
       *
       * <code>UNKNOWN_QUIET_CARRIAGE = 0;</code>
       */
      public static final int UNKNOWN_QUIET_CARRIAGE_VALUE = 0;
      /**
       * <pre>
       * The carriage is designated a quiet carriage.
       * </pre>
       *
       * <code>QUIET_CARRIAGE = 1;</code>
       */
      public static final int QUIET_CARRIAGE_VALUE = 1;
      /**
       * <pre>
       * The carriage is not designated as a quiet carriage.
       * </pre>
       *
       * <code>NOT_QUIET_CARRIAGE = 2;</code>
       */
      public static final int NOT_QUIET_CARRIAGE_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static QuietCarriage valueOf(int value) {
        return forNumber(value);
      }

      public static QuietCarriage forNumber(int value) {
        switch (value) {
          case 0: return UNKNOWN_QUIET_CARRIAGE;
          case 1: return QUIET_CARRIAGE;
          case 2: return NOT_QUIET_CARRIAGE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<QuietCarriage>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          QuietCarriage> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<QuietCarriage>() {
              public QuietCarriage findValueByNumber(int number) {
                return QuietCarriage.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails.getDescriptor().getEnumTypes().get(0);
      }

      private static final QuietCarriage[] VALUES = values();

      public static QuietCarriage valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private QuietCarriage(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:transit_realtime.MtaRailroadCarriageDetails.QuietCarriage)
    }

    /**
     * <pre>
     * Whether the carriage has toilet facilities onboard.
     * </pre>
     *
     * Protobuf enum {@code transit_realtime.MtaRailroadCarriageDetails.ToiletFacilities}
     */
    public enum ToiletFacilities
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * It is unknown if the carriage has toilet facilities. This is the
       * default case.
       * </pre>
       *
       * <code>UNKNOWN_TOILET_FACILITIES = 0;</code>
       */
      UNKNOWN_TOILET_FACILITIES(0),
      /**
       * <pre>
       * The carriage has toilet facilities onboard.
       * </pre>
       *
       * <code>TOILET_ONBOARD = 1;</code>
       */
      TOILET_ONBOARD(1),
      /**
       * <pre>
       * The carriage does not have toilet facilities onboard.
       * </pre>
       *
       * <code>NO_TOILET_ONBOARD = 2;</code>
       */
      NO_TOILET_ONBOARD(2),
      ;

      /**
       * <pre>
       * It is unknown if the carriage has toilet facilities. This is the
       * default case.
       * </pre>
       *
       * <code>UNKNOWN_TOILET_FACILITIES = 0;</code>
       */
      public static final int UNKNOWN_TOILET_FACILITIES_VALUE = 0;
      /**
       * <pre>
       * The carriage has toilet facilities onboard.
       * </pre>
       *
       * <code>TOILET_ONBOARD = 1;</code>
       */
      public static final int TOILET_ONBOARD_VALUE = 1;
      /**
       * <pre>
       * The carriage does not have toilet facilities onboard.
       * </pre>
       *
       * <code>NO_TOILET_ONBOARD = 2;</code>
       */
      public static final int NO_TOILET_ONBOARD_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ToiletFacilities valueOf(int value) {
        return forNumber(value);
      }

      public static ToiletFacilities forNumber(int value) {
        switch (value) {
          case 0: return UNKNOWN_TOILET_FACILITIES;
          case 1: return TOILET_ONBOARD;
          case 2: return NO_TOILET_ONBOARD;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ToiletFacilities>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ToiletFacilities> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ToiletFacilities>() {
              public ToiletFacilities findValueByNumber(int number) {
                return ToiletFacilities.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails.getDescriptor().getEnumTypes().get(1);
      }

      private static final ToiletFacilities[] VALUES = values();

      public static ToiletFacilities valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ToiletFacilities(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:transit_realtime.MtaRailroadCarriageDetails.ToiletFacilities)
    }

    private int bitField0_;
    public static final int BICYCLES_ALLOWED_FIELD_NUMBER = 1;
    private int bicyclesAllowed_;
    /**
     * <pre>
     *Indicates the number of bikes permitted per carriage.
     *0=bikes prohibited, -1=No limit.
     * </pre>
     *
     * <code>optional int32 bicycles_allowed = 1 [default = 0];</code>
     */
    public boolean hasBicyclesAllowed() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *Indicates the number of bikes permitted per carriage.
     *0=bikes prohibited, -1=No limit.
     * </pre>
     *
     * <code>optional int32 bicycles_allowed = 1 [default = 0];</code>
     */
    public int getBicyclesAllowed() {
      return bicyclesAllowed_;
    }

    public static final int CARRIAGE_CLASS_FIELD_NUMBER = 2;
    private volatile java.lang.Object carriageClass_;
    /**
     * <pre>
     *A description of the carriage type/model.
     * </pre>
     *
     * <code>optional string carriage_class = 2;</code>
     */
    public boolean hasCarriageClass() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     *A description of the carriage type/model.
     * </pre>
     *
     * <code>optional string carriage_class = 2;</code>
     */
    public java.lang.String getCarriageClass() {
      java.lang.Object ref = carriageClass_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          carriageClass_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *A description of the carriage type/model.
     * </pre>
     *
     * <code>optional string carriage_class = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCarriageClassBytes() {
      java.lang.Object ref = carriageClass_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        carriageClass_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int QUIET_CARRIAGE_FIELD_NUMBER = 3;
    private int quietCarriage_;
    /**
     * <code>optional .transit_realtime.MtaRailroadCarriageDetails.QuietCarriage quiet_carriage = 3 [default = UNKNOWN_QUIET_CARRIAGE];</code>
     */
    public boolean hasQuietCarriage() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .transit_realtime.MtaRailroadCarriageDetails.QuietCarriage quiet_carriage = 3 [default = UNKNOWN_QUIET_CARRIAGE];</code>
     */
    public com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails.QuietCarriage getQuietCarriage() {
      @SuppressWarnings("deprecation")
      com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails.QuietCarriage result = com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails.QuietCarriage.valueOf(quietCarriage_);
      return result == null ? com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails.QuietCarriage.UNKNOWN_QUIET_CARRIAGE : result;
    }

    public static final int TOILET_FACILITIES_FIELD_NUMBER = 4;
    private int toiletFacilities_;
    /**
     * <code>optional .transit_realtime.MtaRailroadCarriageDetails.ToiletFacilities toilet_facilities = 4 [default = UNKNOWN_TOILET_FACILITIES];</code>
     */
    public boolean hasToiletFacilities() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .transit_realtime.MtaRailroadCarriageDetails.ToiletFacilities toilet_facilities = 4 [default = UNKNOWN_TOILET_FACILITIES];</code>
     */
    public com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails.ToiletFacilities getToiletFacilities() {
      @SuppressWarnings("deprecation")
      com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails.ToiletFacilities result = com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails.ToiletFacilities.valueOf(toiletFacilities_);
      return result == null ? com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails.ToiletFacilities.UNKNOWN_TOILET_FACILITIES : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, bicyclesAllowed_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, carriageClass_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, quietCarriage_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(4, toiletFacilities_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, bicyclesAllowed_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, carriageClass_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, quietCarriage_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, toiletFacilities_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails)) {
        return super.equals(obj);
      }
      com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails other = (com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails) obj;

      boolean result = true;
      result = result && (hasBicyclesAllowed() == other.hasBicyclesAllowed());
      if (hasBicyclesAllowed()) {
        result = result && (getBicyclesAllowed()
            == other.getBicyclesAllowed());
      }
      result = result && (hasCarriageClass() == other.hasCarriageClass());
      if (hasCarriageClass()) {
        result = result && getCarriageClass()
            .equals(other.getCarriageClass());
      }
      result = result && (hasQuietCarriage() == other.hasQuietCarriage());
      if (hasQuietCarriage()) {
        result = result && quietCarriage_ == other.quietCarriage_;
      }
      result = result && (hasToiletFacilities() == other.hasToiletFacilities());
      if (hasToiletFacilities()) {
        result = result && toiletFacilities_ == other.toiletFacilities_;
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasBicyclesAllowed()) {
        hash = (37 * hash) + BICYCLES_ALLOWED_FIELD_NUMBER;
        hash = (53 * hash) + getBicyclesAllowed();
      }
      if (hasCarriageClass()) {
        hash = (37 * hash) + CARRIAGE_CLASS_FIELD_NUMBER;
        hash = (53 * hash) + getCarriageClass().hashCode();
      }
      if (hasQuietCarriage()) {
        hash = (37 * hash) + QUIET_CARRIAGE_FIELD_NUMBER;
        hash = (53 * hash) + quietCarriage_;
      }
      if (hasToiletFacilities()) {
        hash = (37 * hash) + TOILET_FACILITIES_FIELD_NUMBER;
        hash = (53 * hash) + toiletFacilities_;
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code transit_realtime.MtaRailroadCarriageDetails}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:transit_realtime.MtaRailroadCarriageDetails)
        com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetailsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.transit.realtime.GtfsRealtimeMTARR.internal_static_transit_realtime_MtaRailroadCarriageDetails_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.transit.realtime.GtfsRealtimeMTARR.internal_static_transit_realtime_MtaRailroadCarriageDetails_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails.class, com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails.Builder.class);
      }

      // Construct using com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bicyclesAllowed_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        carriageClass_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        quietCarriage_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        toiletFacilities_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.transit.realtime.GtfsRealtimeMTARR.internal_static_transit_realtime_MtaRailroadCarriageDetails_descriptor;
      }

      @java.lang.Override
      public com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails getDefaultInstanceForType() {
        return com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails.getDefaultInstance();
      }

      @java.lang.Override
      public com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails build() {
        com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails buildPartial() {
        com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails result = new com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.bicyclesAllowed_ = bicyclesAllowed_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.carriageClass_ = carriageClass_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.quietCarriage_ = quietCarriage_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.toiletFacilities_ = toiletFacilities_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails) {
          return mergeFrom((com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails other) {
        if (other == com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails.getDefaultInstance()) return this;
        if (other.hasBicyclesAllowed()) {
          setBicyclesAllowed(other.getBicyclesAllowed());
        }
        if (other.hasCarriageClass()) {
          bitField0_ |= 0x00000002;
          carriageClass_ = other.carriageClass_;
          onChanged();
        }
        if (other.hasQuietCarriage()) {
          setQuietCarriage(other.getQuietCarriage());
        }
        if (other.hasToiletFacilities()) {
          setToiletFacilities(other.getToiletFacilities());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int bicyclesAllowed_ ;
      /**
       * <pre>
       *Indicates the number of bikes permitted per carriage.
       *0=bikes prohibited, -1=No limit.
       * </pre>
       *
       * <code>optional int32 bicycles_allowed = 1 [default = 0];</code>
       */
      public boolean hasBicyclesAllowed() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *Indicates the number of bikes permitted per carriage.
       *0=bikes prohibited, -1=No limit.
       * </pre>
       *
       * <code>optional int32 bicycles_allowed = 1 [default = 0];</code>
       */
      public int getBicyclesAllowed() {
        return bicyclesAllowed_;
      }
      /**
       * <pre>
       *Indicates the number of bikes permitted per carriage.
       *0=bikes prohibited, -1=No limit.
       * </pre>
       *
       * <code>optional int32 bicycles_allowed = 1 [default = 0];</code>
       */
      public Builder setBicyclesAllowed(int value) {
        bitField0_ |= 0x00000001;
        bicyclesAllowed_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *Indicates the number of bikes permitted per carriage.
       *0=bikes prohibited, -1=No limit.
       * </pre>
       *
       * <code>optional int32 bicycles_allowed = 1 [default = 0];</code>
       */
      public Builder clearBicyclesAllowed() {
        bitField0_ = (bitField0_ & ~0x00000001);
        bicyclesAllowed_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object carriageClass_ = "";
      /**
       * <pre>
       *A description of the carriage type/model.
       * </pre>
       *
       * <code>optional string carriage_class = 2;</code>
       */
      public boolean hasCarriageClass() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       *A description of the carriage type/model.
       * </pre>
       *
       * <code>optional string carriage_class = 2;</code>
       */
      public java.lang.String getCarriageClass() {
        java.lang.Object ref = carriageClass_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            carriageClass_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *A description of the carriage type/model.
       * </pre>
       *
       * <code>optional string carriage_class = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCarriageClassBytes() {
        java.lang.Object ref = carriageClass_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          carriageClass_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *A description of the carriage type/model.
       * </pre>
       *
       * <code>optional string carriage_class = 2;</code>
       */
      public Builder setCarriageClass(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        carriageClass_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *A description of the carriage type/model.
       * </pre>
       *
       * <code>optional string carriage_class = 2;</code>
       */
      public Builder clearCarriageClass() {
        bitField0_ = (bitField0_ & ~0x00000002);
        carriageClass_ = getDefaultInstance().getCarriageClass();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *A description of the carriage type/model.
       * </pre>
       *
       * <code>optional string carriage_class = 2;</code>
       */
      public Builder setCarriageClassBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        carriageClass_ = value;
        onChanged();
        return this;
      }

      private int quietCarriage_ = 0;
      /**
       * <code>optional .transit_realtime.MtaRailroadCarriageDetails.QuietCarriage quiet_carriage = 3 [default = UNKNOWN_QUIET_CARRIAGE];</code>
       */
      public boolean hasQuietCarriage() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .transit_realtime.MtaRailroadCarriageDetails.QuietCarriage quiet_carriage = 3 [default = UNKNOWN_QUIET_CARRIAGE];</code>
       */
      public com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails.QuietCarriage getQuietCarriage() {
        @SuppressWarnings("deprecation")
        com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails.QuietCarriage result = com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails.QuietCarriage.valueOf(quietCarriage_);
        return result == null ? com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails.QuietCarriage.UNKNOWN_QUIET_CARRIAGE : result;
      }
      /**
       * <code>optional .transit_realtime.MtaRailroadCarriageDetails.QuietCarriage quiet_carriage = 3 [default = UNKNOWN_QUIET_CARRIAGE];</code>
       */
      public Builder setQuietCarriage(com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails.QuietCarriage value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        quietCarriage_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .transit_realtime.MtaRailroadCarriageDetails.QuietCarriage quiet_carriage = 3 [default = UNKNOWN_QUIET_CARRIAGE];</code>
       */
      public Builder clearQuietCarriage() {
        bitField0_ = (bitField0_ & ~0x00000004);
        quietCarriage_ = 0;
        onChanged();
        return this;
      }

      private int toiletFacilities_ = 0;
      /**
       * <code>optional .transit_realtime.MtaRailroadCarriageDetails.ToiletFacilities toilet_facilities = 4 [default = UNKNOWN_TOILET_FACILITIES];</code>
       */
      public boolean hasToiletFacilities() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .transit_realtime.MtaRailroadCarriageDetails.ToiletFacilities toilet_facilities = 4 [default = UNKNOWN_TOILET_FACILITIES];</code>
       */
      public com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails.ToiletFacilities getToiletFacilities() {
        @SuppressWarnings("deprecation")
        com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails.ToiletFacilities result = com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails.ToiletFacilities.valueOf(toiletFacilities_);
        return result == null ? com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails.ToiletFacilities.UNKNOWN_TOILET_FACILITIES : result;
      }
      /**
       * <code>optional .transit_realtime.MtaRailroadCarriageDetails.ToiletFacilities toilet_facilities = 4 [default = UNKNOWN_TOILET_FACILITIES];</code>
       */
      public Builder setToiletFacilities(com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails.ToiletFacilities value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        toiletFacilities_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .transit_realtime.MtaRailroadCarriageDetails.ToiletFacilities toilet_facilities = 4 [default = UNKNOWN_TOILET_FACILITIES];</code>
       */
      public Builder clearToiletFacilities() {
        bitField0_ = (bitField0_ & ~0x00000008);
        toiletFacilities_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:transit_realtime.MtaRailroadCarriageDetails)
    }

    // @@protoc_insertion_point(class_scope:transit_realtime.MtaRailroadCarriageDetails)
    private static final com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails();
    }

    public static com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<MtaRailroadCarriageDetails>
        PARSER = new com.google.protobuf.AbstractParser<MtaRailroadCarriageDetails>() {
      @java.lang.Override
      public MtaRailroadCarriageDetails parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MtaRailroadCarriageDetails(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MtaRailroadCarriageDetails> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MtaRailroadCarriageDetails> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int MTA_RAILROAD_STOP_TIME_UPDATE_FIELD_NUMBER = 1005;
  /**
   * <code>extend .transit_realtime.TripUpdate.StopTimeUpdate { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.transit.realtime.GtfsRealtime.TripUpdate.StopTimeUpdate,
      com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadStopTimeUpdate> mtaRailroadStopTimeUpdate = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadStopTimeUpdate.class,
        com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadStopTimeUpdate.getDefaultInstance());
  public static final int MTA_RAILROAD_CARRIAGE_DETAILS_FIELD_NUMBER = 1005;
  /**
   * <code>extend .transit_realtime.VehiclePosition.CarriageDetails { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.transit.realtime.GtfsRealtime.VehiclePosition.CarriageDetails,
      com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails> mtaRailroadCarriageDetails = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails.class,
        com.google.transit.realtime.GtfsRealtimeMTARR.MtaRailroadCarriageDetails.getDefaultInstance());
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_MtaRailroadStopTimeUpdate_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_MtaRailroadStopTimeUpdate_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_MtaRailroadCarriageDetails_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_MtaRailroadCarriageDetails_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n5com/google/transit/realtime/gtfs-realt" +
      "ime-MTARR.proto\022\020transit_realtime\032/com/g" +
      "oogle/transit/realtime/gtfs-realtime.pro" +
      "to\"?\n\031MtaRailroadStopTimeUpdate\022\r\n\005track" +
      "\030\001 \001(\t\022\023\n\013trainStatus\030\002 \001(\t\"\351\003\n\032MtaRailr" +
      "oadCarriageDetails\022\033\n\020bicycles_allowed\030\001" +
      " \001(\005:\0010\022\026\n\016carriage_class\030\002 \001(\t\022j\n\016quiet" +
      "_carriage\030\003 \001(\0162:.transit_realtime.MtaRa" +
      "ilroadCarriageDetails.QuietCarriage:\026UNK" +
      "NOWN_QUIET_CARRIAGE\022s\n\021toilet_facilities" +
      "\030\004 \001(\0162=.transit_realtime.MtaRailroadCar" +
      "riageDetails.ToiletFacilities:\031UNKNOWN_T" +
      "OILET_FACILITIES\"W\n\rQuietCarriage\022\032\n\026UNK" +
      "NOWN_QUIET_CARRIAGE\020\000\022\022\n\016QUIET_CARRIAGE\020" +
      "\001\022\026\n\022NOT_QUIET_CARRIAGE\020\002\"\\\n\020ToiletFacil" +
      "ities\022\035\n\031UNKNOWN_TOILET_FACILITIES\020\000\022\022\n\016" +
      "TOILET_ONBOARD\020\001\022\025\n\021NO_TOILET_ONBOARD\020\002:" +
      "\200\001\n\035mta_railroad_stop_time_update\022+.tran" +
      "sit_realtime.TripUpdate.StopTimeUpdate\030\355" +
      "\007 \001(\0132+.transit_realtime.MtaRailroadStop" +
      "TimeUpdate:\207\001\n\035mta_railroad_carriage_det" +
      "ails\0221.transit_realtime.VehiclePosition." +
      "CarriageDetails\030\355\007 \001(\0132,.transit_realtim" +
      "e.MtaRailroadCarriageDetailsB\035\n\033com.goog" +
      "le.transit.realtime"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.transit.realtime.GtfsRealtime.getDescriptor(),
        }, assigner);
    internal_static_transit_realtime_MtaRailroadStopTimeUpdate_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_transit_realtime_MtaRailroadStopTimeUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_MtaRailroadStopTimeUpdate_descriptor,
        new java.lang.String[] { "Track", "TrainStatus", });
    internal_static_transit_realtime_MtaRailroadCarriageDetails_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_transit_realtime_MtaRailroadCarriageDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_MtaRailroadCarriageDetails_descriptor,
        new java.lang.String[] { "BicyclesAllowed", "CarriageClass", "QuietCarriage", "ToiletFacilities", });
    mtaRailroadStopTimeUpdate.internalInit(descriptor.getExtensions().get(0));
    mtaRailroadCarriageDetails.internalInit(descriptor.getExtensions().get(1));
    com.google.transit.realtime.GtfsRealtime.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
