/**
 * Portions of this module are modifications based on work created and shared by Google:
 *
 *   http://code.google.com/policies.html
 *
 * and used according to terms described in the Creative Commons 3.0 Attribution License:
 *
 *   http://creativecommons.org/licenses/by/3.0/
 *
 * Specifically, the gtfs-realtime.proto:
 *
 *   http://code.google.com/transit/realtime/docs/gtfs-realtime_proto.html
 *
 * was used to generate the classes contained within.
 *
 * Portions of this module are modifications based on work created by the New York
 * City Metropolitan Transportation Authority.
 *
 * All code is Copyright (C) 2011 Google, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *          http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/google/transit/realtime/gtfs-realtime-service-status.proto

package com.google.transit.realtime;

public final class GtfsRealtimeServiceStatus {
  private GtfsRealtimeServiceStatus() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(com.google.transit.realtime.GtfsRealtimeServiceStatus.mercuryFeedHeader);
    registry.add(com.google.transit.realtime.GtfsRealtimeServiceStatus.mercuryAlert);
    registry.add(com.google.transit.realtime.GtfsRealtimeServiceStatus.mercuryEntitySelector);
  }
  public interface MercuryFeedHeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:transit_realtime.MercuryFeedHeader)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string mercury_version = 1;</code>
     *
     * <pre>
     * Version of the Mercury extensions
     * The current version is 1.0
     * </pre>
     */
    boolean hasMercuryVersion();
    /**
     * <code>required string mercury_version = 1;</code>
     *
     * <pre>
     * Version of the Mercury extensions
     * The current version is 1.0
     * </pre>
     */
    java.lang.String getMercuryVersion();
    /**
     * <code>required string mercury_version = 1;</code>
     *
     * <pre>
     * Version of the Mercury extensions
     * The current version is 1.0
     * </pre>
     */
    com.google.protobuf.ByteString
        getMercuryVersionBytes();
  }
  /**
   * Protobuf type {@code transit_realtime.MercuryFeedHeader}
   *
   * <pre>
   * Mercury extensions for the Feed Header
   * </pre>
   */
  public static final class MercuryFeedHeader extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:transit_realtime.MercuryFeedHeader)
      MercuryFeedHeaderOrBuilder {
    // Use MercuryFeedHeader.newBuilder() to construct.
    private MercuryFeedHeader(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MercuryFeedHeader(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MercuryFeedHeader defaultInstance;
    public static MercuryFeedHeader getDefaultInstance() {
      return defaultInstance;
    }

    public MercuryFeedHeader getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MercuryFeedHeader(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              mercuryVersion_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.transit.realtime.GtfsRealtimeServiceStatus.internal_static_transit_realtime_MercuryFeedHeader_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.transit.realtime.GtfsRealtimeServiceStatus.internal_static_transit_realtime_MercuryFeedHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryFeedHeader.class, com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryFeedHeader.Builder.class);
    }

    public static com.google.protobuf.Parser<MercuryFeedHeader> PARSER =
        new com.google.protobuf.AbstractParser<MercuryFeedHeader>() {
      public MercuryFeedHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MercuryFeedHeader(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MercuryFeedHeader> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int MERCURY_VERSION_FIELD_NUMBER = 1;
    private java.lang.Object mercuryVersion_;
    /**
     * <code>required string mercury_version = 1;</code>
     *
     * <pre>
     * Version of the Mercury extensions
     * The current version is 1.0
     * </pre>
     */
    public boolean hasMercuryVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string mercury_version = 1;</code>
     *
     * <pre>
     * Version of the Mercury extensions
     * The current version is 1.0
     * </pre>
     */
    public java.lang.String getMercuryVersion() {
      java.lang.Object ref = mercuryVersion_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          mercuryVersion_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string mercury_version = 1;</code>
     *
     * <pre>
     * Version of the Mercury extensions
     * The current version is 1.0
     * </pre>
     */
    public com.google.protobuf.ByteString
        getMercuryVersionBytes() {
      java.lang.Object ref = mercuryVersion_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mercuryVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      mercuryVersion_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMercuryVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getMercuryVersionBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getMercuryVersionBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryFeedHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryFeedHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryFeedHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryFeedHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryFeedHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryFeedHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryFeedHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryFeedHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryFeedHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryFeedHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryFeedHeader prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code transit_realtime.MercuryFeedHeader}
     *
     * <pre>
     * Mercury extensions for the Feed Header
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:transit_realtime.MercuryFeedHeader)
        com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryFeedHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.transit.realtime.GtfsRealtimeServiceStatus.internal_static_transit_realtime_MercuryFeedHeader_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.transit.realtime.GtfsRealtimeServiceStatus.internal_static_transit_realtime_MercuryFeedHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryFeedHeader.class, com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryFeedHeader.Builder.class);
      }

      // Construct using com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryFeedHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        mercuryVersion_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.transit.realtime.GtfsRealtimeServiceStatus.internal_static_transit_realtime_MercuryFeedHeader_descriptor;
      }

      public com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryFeedHeader getDefaultInstanceForType() {
        return com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryFeedHeader.getDefaultInstance();
      }

      public com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryFeedHeader build() {
        com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryFeedHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryFeedHeader buildPartial() {
        com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryFeedHeader result = new com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryFeedHeader(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.mercuryVersion_ = mercuryVersion_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryFeedHeader) {
          return mergeFrom((com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryFeedHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryFeedHeader other) {
        if (other == com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryFeedHeader.getDefaultInstance()) return this;
        if (other.hasMercuryVersion()) {
          bitField0_ |= 0x00000001;
          mercuryVersion_ = other.mercuryVersion_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMercuryVersion()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryFeedHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryFeedHeader) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object mercuryVersion_ = "";
      /**
       * <code>required string mercury_version = 1;</code>
       *
       * <pre>
       * Version of the Mercury extensions
       * The current version is 1.0
       * </pre>
       */
      public boolean hasMercuryVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string mercury_version = 1;</code>
       *
       * <pre>
       * Version of the Mercury extensions
       * The current version is 1.0
       * </pre>
       */
      public java.lang.String getMercuryVersion() {
        java.lang.Object ref = mercuryVersion_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            mercuryVersion_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string mercury_version = 1;</code>
       *
       * <pre>
       * Version of the Mercury extensions
       * The current version is 1.0
       * </pre>
       */
      public com.google.protobuf.ByteString
          getMercuryVersionBytes() {
        java.lang.Object ref = mercuryVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mercuryVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string mercury_version = 1;</code>
       *
       * <pre>
       * Version of the Mercury extensions
       * The current version is 1.0
       * </pre>
       */
      public Builder setMercuryVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        mercuryVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string mercury_version = 1;</code>
       *
       * <pre>
       * Version of the Mercury extensions
       * The current version is 1.0
       * </pre>
       */
      public Builder clearMercuryVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        mercuryVersion_ = getDefaultInstance().getMercuryVersion();
        onChanged();
        return this;
      }
      /**
       * <code>required string mercury_version = 1;</code>
       *
       * <pre>
       * Version of the Mercury extensions
       * The current version is 1.0
       * </pre>
       */
      public Builder setMercuryVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        mercuryVersion_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:transit_realtime.MercuryFeedHeader)
    }

    static {
      defaultInstance = new MercuryFeedHeader(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:transit_realtime.MercuryFeedHeader)
  }

  public interface MercuryAlertOrBuilder extends
      // @@protoc_insertion_point(interface_extends:transit_realtime.MercuryAlert)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint64 created_at = 1;</code>
     */
    boolean hasCreatedAt();
    /**
     * <code>required uint64 created_at = 1;</code>
     */
    long getCreatedAt();

    /**
     * <code>required uint64 updated_at = 2;</code>
     */
    boolean hasUpdatedAt();
    /**
     * <code>required uint64 updated_at = 2;</code>
     */
    long getUpdatedAt();

    /**
     * <code>required string alert_type = 3;</code>
     */
    boolean hasAlertType();
    /**
     * <code>required string alert_type = 3;</code>
     */
    java.lang.String getAlertType();
    /**
     * <code>required string alert_type = 3;</code>
     */
    com.google.protobuf.ByteString
        getAlertTypeBytes();
  }
  /**
   * Protobuf type {@code transit_realtime.MercuryAlert}
   *
   * <pre>
   * Mercury extensions for the Feed Alert
   * </pre>
   */
  public static final class MercuryAlert extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:transit_realtime.MercuryAlert)
      MercuryAlertOrBuilder {
    // Use MercuryAlert.newBuilder() to construct.
    private MercuryAlert(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MercuryAlert(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MercuryAlert defaultInstance;
    public static MercuryAlert getDefaultInstance() {
      return defaultInstance;
    }

    public MercuryAlert getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MercuryAlert(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              createdAt_ = input.readUInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              updatedAt_ = input.readUInt64();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              alertType_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.transit.realtime.GtfsRealtimeServiceStatus.internal_static_transit_realtime_MercuryAlert_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.transit.realtime.GtfsRealtimeServiceStatus.internal_static_transit_realtime_MercuryAlert_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryAlert.class, com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryAlert.Builder.class);
    }

    public static com.google.protobuf.Parser<MercuryAlert> PARSER =
        new com.google.protobuf.AbstractParser<MercuryAlert>() {
      public MercuryAlert parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MercuryAlert(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MercuryAlert> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int CREATED_AT_FIELD_NUMBER = 1;
    private long createdAt_;
    /**
     * <code>required uint64 created_at = 1;</code>
     */
    public boolean hasCreatedAt() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint64 created_at = 1;</code>
     */
    public long getCreatedAt() {
      return createdAt_;
    }

    public static final int UPDATED_AT_FIELD_NUMBER = 2;
    private long updatedAt_;
    /**
     * <code>required uint64 updated_at = 2;</code>
     */
    public boolean hasUpdatedAt() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint64 updated_at = 2;</code>
     */
    public long getUpdatedAt() {
      return updatedAt_;
    }

    public static final int ALERT_TYPE_FIELD_NUMBER = 3;
    private java.lang.Object alertType_;
    /**
     * <code>required string alert_type = 3;</code>
     */
    public boolean hasAlertType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string alert_type = 3;</code>
     */
    public java.lang.String getAlertType() {
      java.lang.Object ref = alertType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          alertType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string alert_type = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAlertTypeBytes() {
      java.lang.Object ref = alertType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        alertType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      createdAt_ = 0L;
      updatedAt_ = 0L;
      alertType_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCreatedAt()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUpdatedAt()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAlertType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, createdAt_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, updatedAt_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getAlertTypeBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, createdAt_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, updatedAt_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getAlertTypeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryAlert parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryAlert parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryAlert parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryAlert parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryAlert parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryAlert parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryAlert parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryAlert parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryAlert parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryAlert parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryAlert prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code transit_realtime.MercuryAlert}
     *
     * <pre>
     * Mercury extensions for the Feed Alert
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:transit_realtime.MercuryAlert)
        com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryAlertOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.transit.realtime.GtfsRealtimeServiceStatus.internal_static_transit_realtime_MercuryAlert_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.transit.realtime.GtfsRealtimeServiceStatus.internal_static_transit_realtime_MercuryAlert_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryAlert.class, com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryAlert.Builder.class);
      }

      // Construct using com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryAlert.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        createdAt_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        updatedAt_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        alertType_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.transit.realtime.GtfsRealtimeServiceStatus.internal_static_transit_realtime_MercuryAlert_descriptor;
      }

      public com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryAlert getDefaultInstanceForType() {
        return com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryAlert.getDefaultInstance();
      }

      public com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryAlert build() {
        com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryAlert result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryAlert buildPartial() {
        com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryAlert result = new com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryAlert(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.createdAt_ = createdAt_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.updatedAt_ = updatedAt_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.alertType_ = alertType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryAlert) {
          return mergeFrom((com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryAlert)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryAlert other) {
        if (other == com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryAlert.getDefaultInstance()) return this;
        if (other.hasCreatedAt()) {
          setCreatedAt(other.getCreatedAt());
        }
        if (other.hasUpdatedAt()) {
          setUpdatedAt(other.getUpdatedAt());
        }
        if (other.hasAlertType()) {
          bitField0_ |= 0x00000004;
          alertType_ = other.alertType_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCreatedAt()) {
          
          return false;
        }
        if (!hasUpdatedAt()) {
          
          return false;
        }
        if (!hasAlertType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryAlert parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryAlert) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long createdAt_ ;
      /**
       * <code>required uint64 created_at = 1;</code>
       */
      public boolean hasCreatedAt() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint64 created_at = 1;</code>
       */
      public long getCreatedAt() {
        return createdAt_;
      }
      /**
       * <code>required uint64 created_at = 1;</code>
       */
      public Builder setCreatedAt(long value) {
        bitField0_ |= 0x00000001;
        createdAt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 created_at = 1;</code>
       */
      public Builder clearCreatedAt() {
        bitField0_ = (bitField0_ & ~0x00000001);
        createdAt_ = 0L;
        onChanged();
        return this;
      }

      private long updatedAt_ ;
      /**
       * <code>required uint64 updated_at = 2;</code>
       */
      public boolean hasUpdatedAt() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint64 updated_at = 2;</code>
       */
      public long getUpdatedAt() {
        return updatedAt_;
      }
      /**
       * <code>required uint64 updated_at = 2;</code>
       */
      public Builder setUpdatedAt(long value) {
        bitField0_ |= 0x00000002;
        updatedAt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 updated_at = 2;</code>
       */
      public Builder clearUpdatedAt() {
        bitField0_ = (bitField0_ & ~0x00000002);
        updatedAt_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object alertType_ = "";
      /**
       * <code>required string alert_type = 3;</code>
       */
      public boolean hasAlertType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string alert_type = 3;</code>
       */
      public java.lang.String getAlertType() {
        java.lang.Object ref = alertType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            alertType_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string alert_type = 3;</code>
       */
      public com.google.protobuf.ByteString
          getAlertTypeBytes() {
        java.lang.Object ref = alertType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          alertType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string alert_type = 3;</code>
       */
      public Builder setAlertType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        alertType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string alert_type = 3;</code>
       */
      public Builder clearAlertType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        alertType_ = getDefaultInstance().getAlertType();
        onChanged();
        return this;
      }
      /**
       * <code>required string alert_type = 3;</code>
       */
      public Builder setAlertTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        alertType_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:transit_realtime.MercuryAlert)
    }

    static {
      defaultInstance = new MercuryAlert(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:transit_realtime.MercuryAlert)
  }

  public interface MercuryEntitySelectorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:transit_realtime.MercuryEntitySelector)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string sort_order = 1;</code>
     *
     * <pre>
     * Format for sort_order is 'GTFS-ID:Priority', e.g. 'MTASBWY:G:16'
     * </pre>
     */
    boolean hasSortOrder();
    /**
     * <code>required string sort_order = 1;</code>
     *
     * <pre>
     * Format for sort_order is 'GTFS-ID:Priority', e.g. 'MTASBWY:G:16'
     * </pre>
     */
    java.lang.String getSortOrder();
    /**
     * <code>required string sort_order = 1;</code>
     *
     * <pre>
     * Format for sort_order is 'GTFS-ID:Priority', e.g. 'MTASBWY:G:16'
     * </pre>
     */
    com.google.protobuf.ByteString
        getSortOrderBytes();
  }
  /**
   * Protobuf type {@code transit_realtime.MercuryEntitySelector}
   *
   * <pre>
   * Mercury extensions for the Feed Entity Selector
   * </pre>
   */
  public static final class MercuryEntitySelector extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:transit_realtime.MercuryEntitySelector)
      MercuryEntitySelectorOrBuilder {
    // Use MercuryEntitySelector.newBuilder() to construct.
    private MercuryEntitySelector(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MercuryEntitySelector(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MercuryEntitySelector defaultInstance;
    public static MercuryEntitySelector getDefaultInstance() {
      return defaultInstance;
    }

    public MercuryEntitySelector getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MercuryEntitySelector(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              sortOrder_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.transit.realtime.GtfsRealtimeServiceStatus.internal_static_transit_realtime_MercuryEntitySelector_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.transit.realtime.GtfsRealtimeServiceStatus.internal_static_transit_realtime_MercuryEntitySelector_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryEntitySelector.class, com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryEntitySelector.Builder.class);
    }

    public static com.google.protobuf.Parser<MercuryEntitySelector> PARSER =
        new com.google.protobuf.AbstractParser<MercuryEntitySelector>() {
      public MercuryEntitySelector parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MercuryEntitySelector(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MercuryEntitySelector> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code transit_realtime.MercuryEntitySelector.Priority}
     */
    public enum Priority
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>PRIORITY_NO_SCHEDULED_SERVICE = 1;</code>
       */
      PRIORITY_NO_SCHEDULED_SERVICE(0, 1),
      /**
       * <code>PRIORITY_SUNDAY_SCHEDULE = 2;</code>
       */
      PRIORITY_SUNDAY_SCHEDULE(1, 2),
      /**
       * <code>PRIORITY_SATURDAY_SCHEDULE = 3;</code>
       */
      PRIORITY_SATURDAY_SCHEDULE(2, 3),
      /**
       * <code>PRIORITY_HOLIDAY_SERVICE = 4;</code>
       */
      PRIORITY_HOLIDAY_SERVICE(3, 4),
      /**
       * <code>PRIORITY_EXTRA_SERVICE = 5;</code>
       */
      PRIORITY_EXTRA_SERVICE(4, 5),
      /**
       * <code>PRIORITY_PLANNED_WORK = 6;</code>
       */
      PRIORITY_PLANNED_WORK(5, 6),
      /**
       * <code>PRIORITY_ON_OR_CLOSE = 7;</code>
       */
      PRIORITY_ON_OR_CLOSE(6, 7),
      /**
       * <code>PRIORITY_SLOW_SPEEDS = 8;</code>
       */
      PRIORITY_SLOW_SPEEDS(7, 8),
      /**
       * <code>PRIORITY_SOME_DELAYS = 9;</code>
       */
      PRIORITY_SOME_DELAYS(8, 9),
      /**
       * <code>PRIORITY_SPECIAL_EVENT = 10;</code>
       */
      PRIORITY_SPECIAL_EVENT(9, 10),
      /**
       * <code>PRIORITY_STATIONS_SKIPPED = 11;</code>
       */
      PRIORITY_STATIONS_SKIPPED(10, 11),
      /**
       * <code>PRIORITY_DELAYS = 12;</code>
       */
      PRIORITY_DELAYS(11, 12),
      /**
       * <code>PRIORITY_EXPRESS_TO_LOCAL = 13;</code>
       */
      PRIORITY_EXPRESS_TO_LOCAL(12, 13),
      /**
       * <code>PRIORITY_SOME_REROUTES = 14;</code>
       */
      PRIORITY_SOME_REROUTES(13, 14),
      /**
       * <code>PRIORITY_LOCAL_TO_EXPRESS = 15;</code>
       */
      PRIORITY_LOCAL_TO_EXPRESS(14, 15),
      /**
       * <code>PRIORITY_SERVICE_CHANGE = 16;</code>
       */
      PRIORITY_SERVICE_CHANGE(15, 16),
      /**
       * <code>PRIORITY_TRAINS_REROUTED = 17;</code>
       */
      PRIORITY_TRAINS_REROUTED(16, 17),
      /**
       * <code>PRIORITY_PART_SUSPENDED = 18;</code>
       */
      PRIORITY_PART_SUSPENDED(17, 18),
      /**
       * <code>PRIORITY_MULTIPLE_IMPACTS = 19;</code>
       */
      PRIORITY_MULTIPLE_IMPACTS(18, 19),
      /**
       * <code>PRIORITY_SUSPENDED = 20;</code>
       */
      PRIORITY_SUSPENDED(19, 20),
      /**
       * <code>PRIORITY_BUSING = 21;</code>
       */
      PRIORITY_BUSING(20, 21),
      ;

      /**
       * <code>PRIORITY_NO_SCHEDULED_SERVICE = 1;</code>
       */
      public static final int PRIORITY_NO_SCHEDULED_SERVICE_VALUE = 1;
      /**
       * <code>PRIORITY_SUNDAY_SCHEDULE = 2;</code>
       */
      public static final int PRIORITY_SUNDAY_SCHEDULE_VALUE = 2;
      /**
       * <code>PRIORITY_SATURDAY_SCHEDULE = 3;</code>
       */
      public static final int PRIORITY_SATURDAY_SCHEDULE_VALUE = 3;
      /**
       * <code>PRIORITY_HOLIDAY_SERVICE = 4;</code>
       */
      public static final int PRIORITY_HOLIDAY_SERVICE_VALUE = 4;
      /**
       * <code>PRIORITY_EXTRA_SERVICE = 5;</code>
       */
      public static final int PRIORITY_EXTRA_SERVICE_VALUE = 5;
      /**
       * <code>PRIORITY_PLANNED_WORK = 6;</code>
       */
      public static final int PRIORITY_PLANNED_WORK_VALUE = 6;
      /**
       * <code>PRIORITY_ON_OR_CLOSE = 7;</code>
       */
      public static final int PRIORITY_ON_OR_CLOSE_VALUE = 7;
      /**
       * <code>PRIORITY_SLOW_SPEEDS = 8;</code>
       */
      public static final int PRIORITY_SLOW_SPEEDS_VALUE = 8;
      /**
       * <code>PRIORITY_SOME_DELAYS = 9;</code>
       */
      public static final int PRIORITY_SOME_DELAYS_VALUE = 9;
      /**
       * <code>PRIORITY_SPECIAL_EVENT = 10;</code>
       */
      public static final int PRIORITY_SPECIAL_EVENT_VALUE = 10;
      /**
       * <code>PRIORITY_STATIONS_SKIPPED = 11;</code>
       */
      public static final int PRIORITY_STATIONS_SKIPPED_VALUE = 11;
      /**
       * <code>PRIORITY_DELAYS = 12;</code>
       */
      public static final int PRIORITY_DELAYS_VALUE = 12;
      /**
       * <code>PRIORITY_EXPRESS_TO_LOCAL = 13;</code>
       */
      public static final int PRIORITY_EXPRESS_TO_LOCAL_VALUE = 13;
      /**
       * <code>PRIORITY_SOME_REROUTES = 14;</code>
       */
      public static final int PRIORITY_SOME_REROUTES_VALUE = 14;
      /**
       * <code>PRIORITY_LOCAL_TO_EXPRESS = 15;</code>
       */
      public static final int PRIORITY_LOCAL_TO_EXPRESS_VALUE = 15;
      /**
       * <code>PRIORITY_SERVICE_CHANGE = 16;</code>
       */
      public static final int PRIORITY_SERVICE_CHANGE_VALUE = 16;
      /**
       * <code>PRIORITY_TRAINS_REROUTED = 17;</code>
       */
      public static final int PRIORITY_TRAINS_REROUTED_VALUE = 17;
      /**
       * <code>PRIORITY_PART_SUSPENDED = 18;</code>
       */
      public static final int PRIORITY_PART_SUSPENDED_VALUE = 18;
      /**
       * <code>PRIORITY_MULTIPLE_IMPACTS = 19;</code>
       */
      public static final int PRIORITY_MULTIPLE_IMPACTS_VALUE = 19;
      /**
       * <code>PRIORITY_SUSPENDED = 20;</code>
       */
      public static final int PRIORITY_SUSPENDED_VALUE = 20;
      /**
       * <code>PRIORITY_BUSING = 21;</code>
       */
      public static final int PRIORITY_BUSING_VALUE = 21;


      public final int getNumber() { return value; }

      public static Priority valueOf(int value) {
        switch (value) {
          case 1: return PRIORITY_NO_SCHEDULED_SERVICE;
          case 2: return PRIORITY_SUNDAY_SCHEDULE;
          case 3: return PRIORITY_SATURDAY_SCHEDULE;
          case 4: return PRIORITY_HOLIDAY_SERVICE;
          case 5: return PRIORITY_EXTRA_SERVICE;
          case 6: return PRIORITY_PLANNED_WORK;
          case 7: return PRIORITY_ON_OR_CLOSE;
          case 8: return PRIORITY_SLOW_SPEEDS;
          case 9: return PRIORITY_SOME_DELAYS;
          case 10: return PRIORITY_SPECIAL_EVENT;
          case 11: return PRIORITY_STATIONS_SKIPPED;
          case 12: return PRIORITY_DELAYS;
          case 13: return PRIORITY_EXPRESS_TO_LOCAL;
          case 14: return PRIORITY_SOME_REROUTES;
          case 15: return PRIORITY_LOCAL_TO_EXPRESS;
          case 16: return PRIORITY_SERVICE_CHANGE;
          case 17: return PRIORITY_TRAINS_REROUTED;
          case 18: return PRIORITY_PART_SUSPENDED;
          case 19: return PRIORITY_MULTIPLE_IMPACTS;
          case 20: return PRIORITY_SUSPENDED;
          case 21: return PRIORITY_BUSING;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Priority>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Priority>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Priority>() {
              public Priority findValueByNumber(int number) {
                return Priority.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryEntitySelector.getDescriptor().getEnumTypes().get(0);
      }

      private static final Priority[] VALUES = values();

      public static Priority valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Priority(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:transit_realtime.MercuryEntitySelector.Priority)
    }

    /**
     * Protobuf enum {@code transit_realtime.MercuryEntitySelector.NyctBusPriority}
     */
    public enum NyctBusPriority
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>NYCT_BUS_PRIORITY_NO_SCHEDULED_SERVICE = 1;</code>
       */
      NYCT_BUS_PRIORITY_NO_SCHEDULED_SERVICE(0, 1),
      /**
       * <code>NYCT_BUS_PRIORITY_SUNDAY_SCHEDULE = 2;</code>
       */
      NYCT_BUS_PRIORITY_SUNDAY_SCHEDULE(1, 2),
      /**
       * <code>NYCT_BUS_PRIORITY_SATURDAY_SCHEDULE = 3;</code>
       */
      NYCT_BUS_PRIORITY_SATURDAY_SCHEDULE(2, 3),
      /**
       * <code>NYCT_BUS_PRIORITY_HOLIDAY_SERVICE = 4;</code>
       */
      NYCT_BUS_PRIORITY_HOLIDAY_SERVICE(3, 4),
      /**
       * <code>NYCT_BUS_PRIORITY_PLANNED_DETOUR = 5;</code>
       */
      NYCT_BUS_PRIORITY_PLANNED_DETOUR(4, 5),
      /**
       * <code>NYCT_BUS_PRIORITY_EXTRA_SERVICE = 6;</code>
       */
      NYCT_BUS_PRIORITY_EXTRA_SERVICE(5, 6),
      /**
       * <code>NYCT_BUS_PRIORITY_PLANNED_WORK = 7;</code>
       */
      NYCT_BUS_PRIORITY_PLANNED_WORK(6, 7),
      /**
       * <code>NYCT_BUS_PRIORITY_ON_OR_CLOSE = 8;</code>
       */
      NYCT_BUS_PRIORITY_ON_OR_CLOSE(7, 8),
      /**
       * <code>NYCT_BUS_PRIORITY_SLOW_SPEEDS = 9;</code>
       */
      NYCT_BUS_PRIORITY_SLOW_SPEEDS(8, 9),
      /**
       * <code>NYCT_BUS_PRIORITY_SOME_DELAYS = 10;</code>
       */
      NYCT_BUS_PRIORITY_SOME_DELAYS(9, 10),
      /**
       * <code>NYCT_BUS_PRIORITY_SPECIAL_EVENT = 11;</code>
       */
      NYCT_BUS_PRIORITY_SPECIAL_EVENT(10, 11),
      /**
       * <code>NYCT_BUS_PRIORITY_STATIONS_SKIPPED = 12;</code>
       */
      NYCT_BUS_PRIORITY_STATIONS_SKIPPED(11, 12),
      /**
       * <code>NYCT_BUS_PRIORITY_DELAYS = 13;</code>
       */
      NYCT_BUS_PRIORITY_DELAYS(12, 13),
      /**
       * <code>NYCT_BUS_PRIORITY_EXPRESS_TO_LOCAL = 14;</code>
       */
      NYCT_BUS_PRIORITY_EXPRESS_TO_LOCAL(13, 14),
      /**
       * <code>NYCT_BUS_PRIORITY_SOME_REROUTES = 15;</code>
       */
      NYCT_BUS_PRIORITY_SOME_REROUTES(14, 15),
      /**
       * <code>NYCT_BUS_PRIORITY_DETOUR = 16;</code>
       */
      NYCT_BUS_PRIORITY_DETOUR(15, 16),
      /**
       * <code>NYCT_BUS_PRIORITY_LOCAL_TO_EXPRESS = 17;</code>
       */
      NYCT_BUS_PRIORITY_LOCAL_TO_EXPRESS(16, 17),
      /**
       * <code>NYCT_BUS_PRIORITY_SERVICE_CHANGE = 18;</code>
       */
      NYCT_BUS_PRIORITY_SERVICE_CHANGE(17, 18),
      /**
       * <code>NYCT_BUS_PRIORITY_TRAINS_REROUTED = 19;</code>
       */
      NYCT_BUS_PRIORITY_TRAINS_REROUTED(18, 19),
      /**
       * <code>NYCT_BUS_PRIORITY_PART_SUSPENDED = 20;</code>
       */
      NYCT_BUS_PRIORITY_PART_SUSPENDED(19, 20),
      /**
       * <code>NYCT_BUS_PRIORITY_MULTIPLE_IMPACTS = 21;</code>
       */
      NYCT_BUS_PRIORITY_MULTIPLE_IMPACTS(20, 21),
      /**
       * <code>NYCT_BUS_PRIORITY_SUSPENDED = 22;</code>
       */
      NYCT_BUS_PRIORITY_SUSPENDED(21, 22),
      ;

      /**
       * <code>NYCT_BUS_PRIORITY_NO_SCHEDULED_SERVICE = 1;</code>
       */
      public static final int NYCT_BUS_PRIORITY_NO_SCHEDULED_SERVICE_VALUE = 1;
      /**
       * <code>NYCT_BUS_PRIORITY_SUNDAY_SCHEDULE = 2;</code>
       */
      public static final int NYCT_BUS_PRIORITY_SUNDAY_SCHEDULE_VALUE = 2;
      /**
       * <code>NYCT_BUS_PRIORITY_SATURDAY_SCHEDULE = 3;</code>
       */
      public static final int NYCT_BUS_PRIORITY_SATURDAY_SCHEDULE_VALUE = 3;
      /**
       * <code>NYCT_BUS_PRIORITY_HOLIDAY_SERVICE = 4;</code>
       */
      public static final int NYCT_BUS_PRIORITY_HOLIDAY_SERVICE_VALUE = 4;
      /**
       * <code>NYCT_BUS_PRIORITY_PLANNED_DETOUR = 5;</code>
       */
      public static final int NYCT_BUS_PRIORITY_PLANNED_DETOUR_VALUE = 5;
      /**
       * <code>NYCT_BUS_PRIORITY_EXTRA_SERVICE = 6;</code>
       */
      public static final int NYCT_BUS_PRIORITY_EXTRA_SERVICE_VALUE = 6;
      /**
       * <code>NYCT_BUS_PRIORITY_PLANNED_WORK = 7;</code>
       */
      public static final int NYCT_BUS_PRIORITY_PLANNED_WORK_VALUE = 7;
      /**
       * <code>NYCT_BUS_PRIORITY_ON_OR_CLOSE = 8;</code>
       */
      public static final int NYCT_BUS_PRIORITY_ON_OR_CLOSE_VALUE = 8;
      /**
       * <code>NYCT_BUS_PRIORITY_SLOW_SPEEDS = 9;</code>
       */
      public static final int NYCT_BUS_PRIORITY_SLOW_SPEEDS_VALUE = 9;
      /**
       * <code>NYCT_BUS_PRIORITY_SOME_DELAYS = 10;</code>
       */
      public static final int NYCT_BUS_PRIORITY_SOME_DELAYS_VALUE = 10;
      /**
       * <code>NYCT_BUS_PRIORITY_SPECIAL_EVENT = 11;</code>
       */
      public static final int NYCT_BUS_PRIORITY_SPECIAL_EVENT_VALUE = 11;
      /**
       * <code>NYCT_BUS_PRIORITY_STATIONS_SKIPPED = 12;</code>
       */
      public static final int NYCT_BUS_PRIORITY_STATIONS_SKIPPED_VALUE = 12;
      /**
       * <code>NYCT_BUS_PRIORITY_DELAYS = 13;</code>
       */
      public static final int NYCT_BUS_PRIORITY_DELAYS_VALUE = 13;
      /**
       * <code>NYCT_BUS_PRIORITY_EXPRESS_TO_LOCAL = 14;</code>
       */
      public static final int NYCT_BUS_PRIORITY_EXPRESS_TO_LOCAL_VALUE = 14;
      /**
       * <code>NYCT_BUS_PRIORITY_SOME_REROUTES = 15;</code>
       */
      public static final int NYCT_BUS_PRIORITY_SOME_REROUTES_VALUE = 15;
      /**
       * <code>NYCT_BUS_PRIORITY_DETOUR = 16;</code>
       */
      public static final int NYCT_BUS_PRIORITY_DETOUR_VALUE = 16;
      /**
       * <code>NYCT_BUS_PRIORITY_LOCAL_TO_EXPRESS = 17;</code>
       */
      public static final int NYCT_BUS_PRIORITY_LOCAL_TO_EXPRESS_VALUE = 17;
      /**
       * <code>NYCT_BUS_PRIORITY_SERVICE_CHANGE = 18;</code>
       */
      public static final int NYCT_BUS_PRIORITY_SERVICE_CHANGE_VALUE = 18;
      /**
       * <code>NYCT_BUS_PRIORITY_TRAINS_REROUTED = 19;</code>
       */
      public static final int NYCT_BUS_PRIORITY_TRAINS_REROUTED_VALUE = 19;
      /**
       * <code>NYCT_BUS_PRIORITY_PART_SUSPENDED = 20;</code>
       */
      public static final int NYCT_BUS_PRIORITY_PART_SUSPENDED_VALUE = 20;
      /**
       * <code>NYCT_BUS_PRIORITY_MULTIPLE_IMPACTS = 21;</code>
       */
      public static final int NYCT_BUS_PRIORITY_MULTIPLE_IMPACTS_VALUE = 21;
      /**
       * <code>NYCT_BUS_PRIORITY_SUSPENDED = 22;</code>
       */
      public static final int NYCT_BUS_PRIORITY_SUSPENDED_VALUE = 22;


      public final int getNumber() { return value; }

      public static NyctBusPriority valueOf(int value) {
        switch (value) {
          case 1: return NYCT_BUS_PRIORITY_NO_SCHEDULED_SERVICE;
          case 2: return NYCT_BUS_PRIORITY_SUNDAY_SCHEDULE;
          case 3: return NYCT_BUS_PRIORITY_SATURDAY_SCHEDULE;
          case 4: return NYCT_BUS_PRIORITY_HOLIDAY_SERVICE;
          case 5: return NYCT_BUS_PRIORITY_PLANNED_DETOUR;
          case 6: return NYCT_BUS_PRIORITY_EXTRA_SERVICE;
          case 7: return NYCT_BUS_PRIORITY_PLANNED_WORK;
          case 8: return NYCT_BUS_PRIORITY_ON_OR_CLOSE;
          case 9: return NYCT_BUS_PRIORITY_SLOW_SPEEDS;
          case 10: return NYCT_BUS_PRIORITY_SOME_DELAYS;
          case 11: return NYCT_BUS_PRIORITY_SPECIAL_EVENT;
          case 12: return NYCT_BUS_PRIORITY_STATIONS_SKIPPED;
          case 13: return NYCT_BUS_PRIORITY_DELAYS;
          case 14: return NYCT_BUS_PRIORITY_EXPRESS_TO_LOCAL;
          case 15: return NYCT_BUS_PRIORITY_SOME_REROUTES;
          case 16: return NYCT_BUS_PRIORITY_DETOUR;
          case 17: return NYCT_BUS_PRIORITY_LOCAL_TO_EXPRESS;
          case 18: return NYCT_BUS_PRIORITY_SERVICE_CHANGE;
          case 19: return NYCT_BUS_PRIORITY_TRAINS_REROUTED;
          case 20: return NYCT_BUS_PRIORITY_PART_SUSPENDED;
          case 21: return NYCT_BUS_PRIORITY_MULTIPLE_IMPACTS;
          case 22: return NYCT_BUS_PRIORITY_SUSPENDED;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<NyctBusPriority>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<NyctBusPriority>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<NyctBusPriority>() {
              public NyctBusPriority findValueByNumber(int number) {
                return NyctBusPriority.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryEntitySelector.getDescriptor().getEnumTypes().get(1);
      }

      private static final NyctBusPriority[] VALUES = values();

      public static NyctBusPriority valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private NyctBusPriority(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:transit_realtime.MercuryEntitySelector.NyctBusPriority)
    }

    private int bitField0_;
    public static final int SORT_ORDER_FIELD_NUMBER = 1;
    private java.lang.Object sortOrder_;
    /**
     * <code>required string sort_order = 1;</code>
     *
     * <pre>
     * Format for sort_order is 'GTFS-ID:Priority', e.g. 'MTASBWY:G:16'
     * </pre>
     */
    public boolean hasSortOrder() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string sort_order = 1;</code>
     *
     * <pre>
     * Format for sort_order is 'GTFS-ID:Priority', e.g. 'MTASBWY:G:16'
     * </pre>
     */
    public java.lang.String getSortOrder() {
      java.lang.Object ref = sortOrder_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sortOrder_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string sort_order = 1;</code>
     *
     * <pre>
     * Format for sort_order is 'GTFS-ID:Priority', e.g. 'MTASBWY:G:16'
     * </pre>
     */
    public com.google.protobuf.ByteString
        getSortOrderBytes() {
      java.lang.Object ref = sortOrder_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sortOrder_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      sortOrder_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSortOrder()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getSortOrderBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getSortOrderBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryEntitySelector parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryEntitySelector parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryEntitySelector parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryEntitySelector parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryEntitySelector parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryEntitySelector parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryEntitySelector parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryEntitySelector parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryEntitySelector parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryEntitySelector parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryEntitySelector prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code transit_realtime.MercuryEntitySelector}
     *
     * <pre>
     * Mercury extensions for the Feed Entity Selector
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:transit_realtime.MercuryEntitySelector)
        com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryEntitySelectorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.transit.realtime.GtfsRealtimeServiceStatus.internal_static_transit_realtime_MercuryEntitySelector_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.transit.realtime.GtfsRealtimeServiceStatus.internal_static_transit_realtime_MercuryEntitySelector_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryEntitySelector.class, com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryEntitySelector.Builder.class);
      }

      // Construct using com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryEntitySelector.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        sortOrder_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.transit.realtime.GtfsRealtimeServiceStatus.internal_static_transit_realtime_MercuryEntitySelector_descriptor;
      }

      public com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryEntitySelector getDefaultInstanceForType() {
        return com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryEntitySelector.getDefaultInstance();
      }

      public com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryEntitySelector build() {
        com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryEntitySelector result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryEntitySelector buildPartial() {
        com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryEntitySelector result = new com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryEntitySelector(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sortOrder_ = sortOrder_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryEntitySelector) {
          return mergeFrom((com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryEntitySelector)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryEntitySelector other) {
        if (other == com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryEntitySelector.getDefaultInstance()) return this;
        if (other.hasSortOrder()) {
          bitField0_ |= 0x00000001;
          sortOrder_ = other.sortOrder_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSortOrder()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryEntitySelector parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryEntitySelector) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object sortOrder_ = "";
      /**
       * <code>required string sort_order = 1;</code>
       *
       * <pre>
       * Format for sort_order is 'GTFS-ID:Priority', e.g. 'MTASBWY:G:16'
       * </pre>
       */
      public boolean hasSortOrder() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string sort_order = 1;</code>
       *
       * <pre>
       * Format for sort_order is 'GTFS-ID:Priority', e.g. 'MTASBWY:G:16'
       * </pre>
       */
      public java.lang.String getSortOrder() {
        java.lang.Object ref = sortOrder_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sortOrder_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string sort_order = 1;</code>
       *
       * <pre>
       * Format for sort_order is 'GTFS-ID:Priority', e.g. 'MTASBWY:G:16'
       * </pre>
       */
      public com.google.protobuf.ByteString
          getSortOrderBytes() {
        java.lang.Object ref = sortOrder_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sortOrder_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string sort_order = 1;</code>
       *
       * <pre>
       * Format for sort_order is 'GTFS-ID:Priority', e.g. 'MTASBWY:G:16'
       * </pre>
       */
      public Builder setSortOrder(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sortOrder_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string sort_order = 1;</code>
       *
       * <pre>
       * Format for sort_order is 'GTFS-ID:Priority', e.g. 'MTASBWY:G:16'
       * </pre>
       */
      public Builder clearSortOrder() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sortOrder_ = getDefaultInstance().getSortOrder();
        onChanged();
        return this;
      }
      /**
       * <code>required string sort_order = 1;</code>
       *
       * <pre>
       * Format for sort_order is 'GTFS-ID:Priority', e.g. 'MTASBWY:G:16'
       * </pre>
       */
      public Builder setSortOrderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sortOrder_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:transit_realtime.MercuryEntitySelector)
    }

    static {
      defaultInstance = new MercuryEntitySelector(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:transit_realtime.MercuryEntitySelector)
  }

  public static final int MERCURY_FEED_HEADER_FIELD_NUMBER = 1001;
  /**
   * <code>extend .transit_realtime.FeedHeader { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.transit.realtime.GtfsRealtime.FeedHeader,
      com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryFeedHeader> mercuryFeedHeader = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryFeedHeader.class,
        com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryFeedHeader.getDefaultInstance());
  public static final int MERCURY_ALERT_FIELD_NUMBER = 1001;
  /**
   * <code>extend .transit_realtime.Alert { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.transit.realtime.GtfsRealtime.Alert,
      com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryAlert> mercuryAlert = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryAlert.class,
        com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryAlert.getDefaultInstance());
  public static final int MERCURY_ENTITY_SELECTOR_FIELD_NUMBER = 1001;
  /**
   * <code>extend .transit_realtime.EntitySelector { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.transit.realtime.GtfsRealtime.EntitySelector,
      com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryEntitySelector> mercuryEntitySelector = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryEntitySelector.class,
        com.google.transit.realtime.GtfsRealtimeServiceStatus.MercuryEntitySelector.getDefaultInstance());
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_MercuryFeedHeader_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_transit_realtime_MercuryFeedHeader_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_MercuryAlert_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_transit_realtime_MercuryAlert_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_MercuryEntitySelector_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_transit_realtime_MercuryEntitySelector_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n>com/google/transit/realtime/gtfs-realt" +
      "ime-service-status.proto\022\020transit_realti" +
      "me\032/com/google/transit/realtime/gtfs-rea" +
      "ltime.proto\",\n\021MercuryFeedHeader\022\027\n\017merc" +
      "ury_version\030\001 \002(\t\"J\n\014MercuryAlert\022\022\n\ncre" +
      "ated_at\030\001 \002(\004\022\022\n\nupdated_at\030\002 \002(\004\022\022\n\nale" +
      "rt_type\030\003 \002(\t\"\323\013\n\025MercuryEntitySelector\022" +
      "\022\n\nsort_order\030\001 \002(\t\"\334\004\n\010Priority\022!\n\035PRIO" +
      "RITY_NO_SCHEDULED_SERVICE\020\001\022\034\n\030PRIORITY_" +
      "SUNDAY_SCHEDULE\020\002\022\036\n\032PRIORITY_SATURDAY_S",
      "CHEDULE\020\003\022\034\n\030PRIORITY_HOLIDAY_SERVICE\020\004\022" +
      "\032\n\026PRIORITY_EXTRA_SERVICE\020\005\022\031\n\025PRIORITY_" +
      "PLANNED_WORK\020\006\022\030\n\024PRIORITY_ON_OR_CLOSE\020\007" +
      "\022\030\n\024PRIORITY_SLOW_SPEEDS\020\010\022\030\n\024PRIORITY_S" +
      "OME_DELAYS\020\t\022\032\n\026PRIORITY_SPECIAL_EVENT\020\n" +
      "\022\035\n\031PRIORITY_STATIONS_SKIPPED\020\013\022\023\n\017PRIOR" +
      "ITY_DELAYS\020\014\022\035\n\031PRIORITY_EXPRESS_TO_LOCA" +
      "L\020\r\022\032\n\026PRIORITY_SOME_REROUTES\020\016\022\035\n\031PRIOR" +
      "ITY_LOCAL_TO_EXPRESS\020\017\022\033\n\027PRIORITY_SERVI" +
      "CE_CHANGE\020\020\022\034\n\030PRIORITY_TRAINS_REROUTED\020",
      "\021\022\033\n\027PRIORITY_PART_SUSPENDED\020\022\022\035\n\031PRIORI" +
      "TY_MULTIPLE_IMPACTS\020\023\022\026\n\022PRIORITY_SUSPEN" +
      "DED\020\024\022\023\n\017PRIORITY_BUSING\020\025\"\306\006\n\017NyctBusPr" +
      "iority\022*\n&NYCT_BUS_PRIORITY_NO_SCHEDULED" +
      "_SERVICE\020\001\022%\n!NYCT_BUS_PRIORITY_SUNDAY_S" +
      "CHEDULE\020\002\022\'\n#NYCT_BUS_PRIORITY_SATURDAY_" +
      "SCHEDULE\020\003\022%\n!NYCT_BUS_PRIORITY_HOLIDAY_" +
      "SERVICE\020\004\022$\n NYCT_BUS_PRIORITY_PLANNED_D" +
      "ETOUR\020\005\022#\n\037NYCT_BUS_PRIORITY_EXTRA_SERVI" +
      "CE\020\006\022\"\n\036NYCT_BUS_PRIORITY_PLANNED_WORK\020\007",
      "\022!\n\035NYCT_BUS_PRIORITY_ON_OR_CLOSE\020\010\022!\n\035N" +
      "YCT_BUS_PRIORITY_SLOW_SPEEDS\020\t\022!\n\035NYCT_B" +
      "US_PRIORITY_SOME_DELAYS\020\n\022#\n\037NYCT_BUS_PR" +
      "IORITY_SPECIAL_EVENT\020\013\022&\n\"NYCT_BUS_PRIOR" +
      "ITY_STATIONS_SKIPPED\020\014\022\034\n\030NYCT_BUS_PRIOR" +
      "ITY_DELAYS\020\r\022&\n\"NYCT_BUS_PRIORITY_EXPRES" +
      "S_TO_LOCAL\020\016\022#\n\037NYCT_BUS_PRIORITY_SOME_R" +
      "EROUTES\020\017\022\034\n\030NYCT_BUS_PRIORITY_DETOUR\020\020\022" +
      "&\n\"NYCT_BUS_PRIORITY_LOCAL_TO_EXPRESS\020\021\022" +
      "$\n NYCT_BUS_PRIORITY_SERVICE_CHANGE\020\022\022%\n",
      "!NYCT_BUS_PRIORITY_TRAINS_REROUTED\020\023\022$\n " +
      "NYCT_BUS_PRIORITY_PART_SUSPENDED\020\024\022&\n\"NY" +
      "CT_BUS_PRIORITY_MULTIPLE_IMPACTS\020\025\022\037\n\033NY" +
      "CT_BUS_PRIORITY_SUSPENDED\020\026:_\n\023mercury_f" +
      "eed_header\022\034.transit_realtime.FeedHeader" +
      "\030\351\007 \001(\0132#.transit_realtime.MercuryFeedHe" +
      "ader:O\n\rmercury_alert\022\027.transit_realtime" +
      ".Alert\030\351\007 \001(\0132\036.transit_realtime.Mercury" +
      "Alert:k\n\027mercury_entity_selector\022 .trans" +
      "it_realtime.EntitySelector\030\351\007 \001(\0132\'.tran",
      "sit_realtime.MercuryEntitySelectorB\035\n\033co" +
      "m.google.transit.realtime"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.transit.realtime.GtfsRealtime.getDescriptor(),
        }, assigner);
    internal_static_transit_realtime_MercuryFeedHeader_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_transit_realtime_MercuryFeedHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_transit_realtime_MercuryFeedHeader_descriptor,
        new java.lang.String[] { "MercuryVersion", });
    internal_static_transit_realtime_MercuryAlert_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_transit_realtime_MercuryAlert_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_transit_realtime_MercuryAlert_descriptor,
        new java.lang.String[] { "CreatedAt", "UpdatedAt", "AlertType", });
    internal_static_transit_realtime_MercuryEntitySelector_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_transit_realtime_MercuryEntitySelector_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_transit_realtime_MercuryEntitySelector_descriptor,
        new java.lang.String[] { "SortOrder", });
    mercuryFeedHeader.internalInit(descriptor.getExtensions().get(0));
    mercuryAlert.internalInit(descriptor.getExtensions().get(1));
    mercuryEntitySelector.internalInit(descriptor.getExtensions().get(2));
    com.google.transit.realtime.GtfsRealtime.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
