// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/google/transit/realtime/gtfs-realtime-NYCT.proto

package com.google.transit.realtime;

public final class GtfsRealtimeNYCT {
  private GtfsRealtimeNYCT() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(com.google.transit.realtime.GtfsRealtimeNYCT.nyctFeedHeader);
    registry.add(com.google.transit.realtime.GtfsRealtimeNYCT.nyctTripDescriptor);
    registry.add(com.google.transit.realtime.GtfsRealtimeNYCT.nyctStopTimeUpdate);
  }
  public interface TripReplacementPeriodOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string route_id = 1;
    boolean hasRouteId();
    String getRouteId();
    
    // optional .transit_realtime.TimeRange replacement_period = 2;
    boolean hasReplacementPeriod();
    com.google.transit.realtime.GtfsRealtime.TimeRange getReplacementPeriod();
    com.google.transit.realtime.GtfsRealtime.TimeRangeOrBuilder getReplacementPeriodOrBuilder();
  }
  public static final class TripReplacementPeriod extends
      com.google.protobuf.GeneratedMessage
      implements TripReplacementPeriodOrBuilder {
    // Use TripReplacementPeriod.newBuilder() to construct.
    private TripReplacementPeriod(Builder builder) {
      super(builder);
    }
    private TripReplacementPeriod(boolean noInit) {}
    
    private static final TripReplacementPeriod defaultInstance;
    public static TripReplacementPeriod getDefaultInstance() {
      return defaultInstance;
    }
    
    public TripReplacementPeriod getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.transit.realtime.GtfsRealtimeNYCT.internal_static_transit_realtime_TripReplacementPeriod_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.transit.realtime.GtfsRealtimeNYCT.internal_static_transit_realtime_TripReplacementPeriod_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string route_id = 1;
    public static final int ROUTE_ID_FIELD_NUMBER = 1;
    private java.lang.Object routeId_;
    public boolean hasRouteId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getRouteId() {
      java.lang.Object ref = routeId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          routeId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getRouteIdBytes() {
      java.lang.Object ref = routeId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        routeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional .transit_realtime.TimeRange replacement_period = 2;
    public static final int REPLACEMENT_PERIOD_FIELD_NUMBER = 2;
    private com.google.transit.realtime.GtfsRealtime.TimeRange replacementPeriod_;
    public boolean hasReplacementPeriod() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.google.transit.realtime.GtfsRealtime.TimeRange getReplacementPeriod() {
      return replacementPeriod_;
    }
    public com.google.transit.realtime.GtfsRealtime.TimeRangeOrBuilder getReplacementPeriodOrBuilder() {
      return replacementPeriod_;
    }
    
    private void initFields() {
      routeId_ = "";
      replacementPeriod_ = com.google.transit.realtime.GtfsRealtime.TimeRange.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getRouteIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, replacementPeriod_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getRouteIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, replacementPeriod_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriodOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.transit.realtime.GtfsRealtimeNYCT.internal_static_transit_realtime_TripReplacementPeriod_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.transit.realtime.GtfsRealtimeNYCT.internal_static_transit_realtime_TripReplacementPeriod_fieldAccessorTable;
      }
      
      // Construct using com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getReplacementPeriodFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        routeId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (replacementPeriodBuilder_ == null) {
          replacementPeriod_ = com.google.transit.realtime.GtfsRealtime.TimeRange.getDefaultInstance();
        } else {
          replacementPeriodBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod.getDescriptor();
      }
      
      public com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod getDefaultInstanceForType() {
        return com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod.getDefaultInstance();
      }
      
      public com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod build() {
        com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod buildPartial() {
        com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod result = new com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.routeId_ = routeId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (replacementPeriodBuilder_ == null) {
          result.replacementPeriod_ = replacementPeriod_;
        } else {
          result.replacementPeriod_ = replacementPeriodBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod) {
          return mergeFrom((com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod other) {
        if (other == com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod.getDefaultInstance()) return this;
        if (other.hasRouteId()) {
          setRouteId(other.getRouteId());
        }
        if (other.hasReplacementPeriod()) {
          mergeReplacementPeriod(other.getReplacementPeriod());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              routeId_ = input.readBytes();
              break;
            }
            case 18: {
              com.google.transit.realtime.GtfsRealtime.TimeRange.Builder subBuilder = com.google.transit.realtime.GtfsRealtime.TimeRange.newBuilder();
              if (hasReplacementPeriod()) {
                subBuilder.mergeFrom(getReplacementPeriod());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setReplacementPeriod(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string route_id = 1;
      private java.lang.Object routeId_ = "";
      public boolean hasRouteId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getRouteId() {
        java.lang.Object ref = routeId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          routeId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setRouteId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        routeId_ = value;
        onChanged();
        return this;
      }
      public Builder clearRouteId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        routeId_ = getDefaultInstance().getRouteId();
        onChanged();
        return this;
      }
      void setRouteId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        routeId_ = value;
        onChanged();
      }
      
      // optional .transit_realtime.TimeRange replacement_period = 2;
      private com.google.transit.realtime.GtfsRealtime.TimeRange replacementPeriod_ = com.google.transit.realtime.GtfsRealtime.TimeRange.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.google.transit.realtime.GtfsRealtime.TimeRange, com.google.transit.realtime.GtfsRealtime.TimeRange.Builder, com.google.transit.realtime.GtfsRealtime.TimeRangeOrBuilder> replacementPeriodBuilder_;
      public boolean hasReplacementPeriod() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.google.transit.realtime.GtfsRealtime.TimeRange getReplacementPeriod() {
        if (replacementPeriodBuilder_ == null) {
          return replacementPeriod_;
        } else {
          return replacementPeriodBuilder_.getMessage();
        }
      }
      public Builder setReplacementPeriod(com.google.transit.realtime.GtfsRealtime.TimeRange value) {
        if (replacementPeriodBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          replacementPeriod_ = value;
          onChanged();
        } else {
          replacementPeriodBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setReplacementPeriod(
          com.google.transit.realtime.GtfsRealtime.TimeRange.Builder builderForValue) {
        if (replacementPeriodBuilder_ == null) {
          replacementPeriod_ = builderForValue.build();
          onChanged();
        } else {
          replacementPeriodBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeReplacementPeriod(com.google.transit.realtime.GtfsRealtime.TimeRange value) {
        if (replacementPeriodBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              replacementPeriod_ != com.google.transit.realtime.GtfsRealtime.TimeRange.getDefaultInstance()) {
            replacementPeriod_ =
              com.google.transit.realtime.GtfsRealtime.TimeRange.newBuilder(replacementPeriod_).mergeFrom(value).buildPartial();
          } else {
            replacementPeriod_ = value;
          }
          onChanged();
        } else {
          replacementPeriodBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearReplacementPeriod() {
        if (replacementPeriodBuilder_ == null) {
          replacementPeriod_ = com.google.transit.realtime.GtfsRealtime.TimeRange.getDefaultInstance();
          onChanged();
        } else {
          replacementPeriodBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public com.google.transit.realtime.GtfsRealtime.TimeRange.Builder getReplacementPeriodBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getReplacementPeriodFieldBuilder().getBuilder();
      }
      public com.google.transit.realtime.GtfsRealtime.TimeRangeOrBuilder getReplacementPeriodOrBuilder() {
        if (replacementPeriodBuilder_ != null) {
          return replacementPeriodBuilder_.getMessageOrBuilder();
        } else {
          return replacementPeriod_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.google.transit.realtime.GtfsRealtime.TimeRange, com.google.transit.realtime.GtfsRealtime.TimeRange.Builder, com.google.transit.realtime.GtfsRealtime.TimeRangeOrBuilder> 
          getReplacementPeriodFieldBuilder() {
        if (replacementPeriodBuilder_ == null) {
          replacementPeriodBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.google.transit.realtime.GtfsRealtime.TimeRange, com.google.transit.realtime.GtfsRealtime.TimeRange.Builder, com.google.transit.realtime.GtfsRealtime.TimeRangeOrBuilder>(
                  replacementPeriod_,
                  getParentForChildren(),
                  isClean());
          replacementPeriod_ = null;
        }
        return replacementPeriodBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:transit_realtime.TripReplacementPeriod)
    }
    
    static {
      defaultInstance = new TripReplacementPeriod(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:transit_realtime.TripReplacementPeriod)
  }
  
  public interface NyctFeedHeaderOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string nyct_subway_version = 1;
    boolean hasNyctSubwayVersion();
    String getNyctSubwayVersion();
    
    // repeated .transit_realtime.TripReplacementPeriod trip_replacement_period = 2;
    java.util.List<com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod> 
        getTripReplacementPeriodList();
    com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod getTripReplacementPeriod(int index);
    int getTripReplacementPeriodCount();
    java.util.List<? extends com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriodOrBuilder> 
        getTripReplacementPeriodOrBuilderList();
    com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriodOrBuilder getTripReplacementPeriodOrBuilder(
        int index);
  }
  public static final class NyctFeedHeader extends
      com.google.protobuf.GeneratedMessage
      implements NyctFeedHeaderOrBuilder {
    // Use NyctFeedHeader.newBuilder() to construct.
    private NyctFeedHeader(Builder builder) {
      super(builder);
    }
    private NyctFeedHeader(boolean noInit) {}
    
    private static final NyctFeedHeader defaultInstance;
    public static NyctFeedHeader getDefaultInstance() {
      return defaultInstance;
    }
    
    public NyctFeedHeader getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.transit.realtime.GtfsRealtimeNYCT.internal_static_transit_realtime_NyctFeedHeader_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.transit.realtime.GtfsRealtimeNYCT.internal_static_transit_realtime_NyctFeedHeader_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string nyct_subway_version = 1;
    public static final int NYCT_SUBWAY_VERSION_FIELD_NUMBER = 1;
    private java.lang.Object nyctSubwayVersion_;
    public boolean hasNyctSubwayVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getNyctSubwayVersion() {
      java.lang.Object ref = nyctSubwayVersion_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          nyctSubwayVersion_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNyctSubwayVersionBytes() {
      java.lang.Object ref = nyctSubwayVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        nyctSubwayVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .transit_realtime.TripReplacementPeriod trip_replacement_period = 2;
    public static final int TRIP_REPLACEMENT_PERIOD_FIELD_NUMBER = 2;
    private java.util.List<com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod> tripReplacementPeriod_;
    public java.util.List<com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod> getTripReplacementPeriodList() {
      return tripReplacementPeriod_;
    }
    public java.util.List<? extends com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriodOrBuilder> 
        getTripReplacementPeriodOrBuilderList() {
      return tripReplacementPeriod_;
    }
    public int getTripReplacementPeriodCount() {
      return tripReplacementPeriod_.size();
    }
    public com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod getTripReplacementPeriod(int index) {
      return tripReplacementPeriod_.get(index);
    }
    public com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriodOrBuilder getTripReplacementPeriodOrBuilder(
        int index) {
      return tripReplacementPeriod_.get(index);
    }
    
    private void initFields() {
      nyctSubwayVersion_ = "";
      tripReplacementPeriod_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasNyctSubwayVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNyctSubwayVersionBytes());
      }
      for (int i = 0; i < tripReplacementPeriod_.size(); i++) {
        output.writeMessage(2, tripReplacementPeriod_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNyctSubwayVersionBytes());
      }
      for (int i = 0; i < tripReplacementPeriod_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, tripReplacementPeriod_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.google.transit.realtime.GtfsRealtimeNYCT.NyctFeedHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.transit.realtime.GtfsRealtimeNYCT.NyctFeedHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.transit.realtime.GtfsRealtimeNYCT.NyctFeedHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.transit.realtime.GtfsRealtimeNYCT.NyctFeedHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.transit.realtime.GtfsRealtimeNYCT.NyctFeedHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.transit.realtime.GtfsRealtimeNYCT.NyctFeedHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.google.transit.realtime.GtfsRealtimeNYCT.NyctFeedHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.transit.realtime.GtfsRealtimeNYCT.NyctFeedHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.transit.realtime.GtfsRealtimeNYCT.NyctFeedHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.transit.realtime.GtfsRealtimeNYCT.NyctFeedHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.transit.realtime.GtfsRealtimeNYCT.NyctFeedHeader prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.google.transit.realtime.GtfsRealtimeNYCT.NyctFeedHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.transit.realtime.GtfsRealtimeNYCT.internal_static_transit_realtime_NyctFeedHeader_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.transit.realtime.GtfsRealtimeNYCT.internal_static_transit_realtime_NyctFeedHeader_fieldAccessorTable;
      }
      
      // Construct using com.google.transit.realtime.GtfsRealtimeNYCT.NyctFeedHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTripReplacementPeriodFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        nyctSubwayVersion_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (tripReplacementPeriodBuilder_ == null) {
          tripReplacementPeriod_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          tripReplacementPeriodBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.transit.realtime.GtfsRealtimeNYCT.NyctFeedHeader.getDescriptor();
      }
      
      public com.google.transit.realtime.GtfsRealtimeNYCT.NyctFeedHeader getDefaultInstanceForType() {
        return com.google.transit.realtime.GtfsRealtimeNYCT.NyctFeedHeader.getDefaultInstance();
      }
      
      public com.google.transit.realtime.GtfsRealtimeNYCT.NyctFeedHeader build() {
        com.google.transit.realtime.GtfsRealtimeNYCT.NyctFeedHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.google.transit.realtime.GtfsRealtimeNYCT.NyctFeedHeader buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.google.transit.realtime.GtfsRealtimeNYCT.NyctFeedHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.google.transit.realtime.GtfsRealtimeNYCT.NyctFeedHeader buildPartial() {
        com.google.transit.realtime.GtfsRealtimeNYCT.NyctFeedHeader result = new com.google.transit.realtime.GtfsRealtimeNYCT.NyctFeedHeader(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.nyctSubwayVersion_ = nyctSubwayVersion_;
        if (tripReplacementPeriodBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            tripReplacementPeriod_ = java.util.Collections.unmodifiableList(tripReplacementPeriod_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.tripReplacementPeriod_ = tripReplacementPeriod_;
        } else {
          result.tripReplacementPeriod_ = tripReplacementPeriodBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.transit.realtime.GtfsRealtimeNYCT.NyctFeedHeader) {
          return mergeFrom((com.google.transit.realtime.GtfsRealtimeNYCT.NyctFeedHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.google.transit.realtime.GtfsRealtimeNYCT.NyctFeedHeader other) {
        if (other == com.google.transit.realtime.GtfsRealtimeNYCT.NyctFeedHeader.getDefaultInstance()) return this;
        if (other.hasNyctSubwayVersion()) {
          setNyctSubwayVersion(other.getNyctSubwayVersion());
        }
        if (tripReplacementPeriodBuilder_ == null) {
          if (!other.tripReplacementPeriod_.isEmpty()) {
            if (tripReplacementPeriod_.isEmpty()) {
              tripReplacementPeriod_ = other.tripReplacementPeriod_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureTripReplacementPeriodIsMutable();
              tripReplacementPeriod_.addAll(other.tripReplacementPeriod_);
            }
            onChanged();
          }
        } else {
          if (!other.tripReplacementPeriod_.isEmpty()) {
            if (tripReplacementPeriodBuilder_.isEmpty()) {
              tripReplacementPeriodBuilder_.dispose();
              tripReplacementPeriodBuilder_ = null;
              tripReplacementPeriod_ = other.tripReplacementPeriod_;
              bitField0_ = (bitField0_ & ~0x00000002);
              tripReplacementPeriodBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getTripReplacementPeriodFieldBuilder() : null;
            } else {
              tripReplacementPeriodBuilder_.addAllMessages(other.tripReplacementPeriod_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasNyctSubwayVersion()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              nyctSubwayVersion_ = input.readBytes();
              break;
            }
            case 18: {
              com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod.Builder subBuilder = com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addTripReplacementPeriod(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string nyct_subway_version = 1;
      private java.lang.Object nyctSubwayVersion_ = "";
      public boolean hasNyctSubwayVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getNyctSubwayVersion() {
        java.lang.Object ref = nyctSubwayVersion_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          nyctSubwayVersion_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setNyctSubwayVersion(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        nyctSubwayVersion_ = value;
        onChanged();
        return this;
      }
      public Builder clearNyctSubwayVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        nyctSubwayVersion_ = getDefaultInstance().getNyctSubwayVersion();
        onChanged();
        return this;
      }
      void setNyctSubwayVersion(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        nyctSubwayVersion_ = value;
        onChanged();
      }
      
      // repeated .transit_realtime.TripReplacementPeriod trip_replacement_period = 2;
      private java.util.List<com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod> tripReplacementPeriod_ =
        java.util.Collections.emptyList();
      private void ensureTripReplacementPeriodIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          tripReplacementPeriod_ = new java.util.ArrayList<com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod>(tripReplacementPeriod_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod, com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod.Builder, com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriodOrBuilder> tripReplacementPeriodBuilder_;
      
      public java.util.List<com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod> getTripReplacementPeriodList() {
        if (tripReplacementPeriodBuilder_ == null) {
          return java.util.Collections.unmodifiableList(tripReplacementPeriod_);
        } else {
          return tripReplacementPeriodBuilder_.getMessageList();
        }
      }
      public int getTripReplacementPeriodCount() {
        if (tripReplacementPeriodBuilder_ == null) {
          return tripReplacementPeriod_.size();
        } else {
          return tripReplacementPeriodBuilder_.getCount();
        }
      }
      public com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod getTripReplacementPeriod(int index) {
        if (tripReplacementPeriodBuilder_ == null) {
          return tripReplacementPeriod_.get(index);
        } else {
          return tripReplacementPeriodBuilder_.getMessage(index);
        }
      }
      public Builder setTripReplacementPeriod(
          int index, com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod value) {
        if (tripReplacementPeriodBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTripReplacementPeriodIsMutable();
          tripReplacementPeriod_.set(index, value);
          onChanged();
        } else {
          tripReplacementPeriodBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setTripReplacementPeriod(
          int index, com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod.Builder builderForValue) {
        if (tripReplacementPeriodBuilder_ == null) {
          ensureTripReplacementPeriodIsMutable();
          tripReplacementPeriod_.set(index, builderForValue.build());
          onChanged();
        } else {
          tripReplacementPeriodBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addTripReplacementPeriod(com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod value) {
        if (tripReplacementPeriodBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTripReplacementPeriodIsMutable();
          tripReplacementPeriod_.add(value);
          onChanged();
        } else {
          tripReplacementPeriodBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addTripReplacementPeriod(
          int index, com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod value) {
        if (tripReplacementPeriodBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTripReplacementPeriodIsMutable();
          tripReplacementPeriod_.add(index, value);
          onChanged();
        } else {
          tripReplacementPeriodBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addTripReplacementPeriod(
          com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod.Builder builderForValue) {
        if (tripReplacementPeriodBuilder_ == null) {
          ensureTripReplacementPeriodIsMutable();
          tripReplacementPeriod_.add(builderForValue.build());
          onChanged();
        } else {
          tripReplacementPeriodBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addTripReplacementPeriod(
          int index, com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod.Builder builderForValue) {
        if (tripReplacementPeriodBuilder_ == null) {
          ensureTripReplacementPeriodIsMutable();
          tripReplacementPeriod_.add(index, builderForValue.build());
          onChanged();
        } else {
          tripReplacementPeriodBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllTripReplacementPeriod(
          java.lang.Iterable<? extends com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod> values) {
        if (tripReplacementPeriodBuilder_ == null) {
          ensureTripReplacementPeriodIsMutable();
          super.addAll(values, tripReplacementPeriod_);
          onChanged();
        } else {
          tripReplacementPeriodBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearTripReplacementPeriod() {
        if (tripReplacementPeriodBuilder_ == null) {
          tripReplacementPeriod_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          tripReplacementPeriodBuilder_.clear();
        }
        return this;
      }
      public Builder removeTripReplacementPeriod(int index) {
        if (tripReplacementPeriodBuilder_ == null) {
          ensureTripReplacementPeriodIsMutable();
          tripReplacementPeriod_.remove(index);
          onChanged();
        } else {
          tripReplacementPeriodBuilder_.remove(index);
        }
        return this;
      }
      public com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod.Builder getTripReplacementPeriodBuilder(
          int index) {
        return getTripReplacementPeriodFieldBuilder().getBuilder(index);
      }
      public com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriodOrBuilder getTripReplacementPeriodOrBuilder(
          int index) {
        if (tripReplacementPeriodBuilder_ == null) {
          return tripReplacementPeriod_.get(index);  } else {
          return tripReplacementPeriodBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriodOrBuilder> 
           getTripReplacementPeriodOrBuilderList() {
        if (tripReplacementPeriodBuilder_ != null) {
          return tripReplacementPeriodBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(tripReplacementPeriod_);
        }
      }
      public com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod.Builder addTripReplacementPeriodBuilder() {
        return getTripReplacementPeriodFieldBuilder().addBuilder(
            com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod.getDefaultInstance());
      }
      public com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod.Builder addTripReplacementPeriodBuilder(
          int index) {
        return getTripReplacementPeriodFieldBuilder().addBuilder(
            index, com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod.getDefaultInstance());
      }
      public java.util.List<com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod.Builder> 
           getTripReplacementPeriodBuilderList() {
        return getTripReplacementPeriodFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod, com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod.Builder, com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriodOrBuilder> 
          getTripReplacementPeriodFieldBuilder() {
        if (tripReplacementPeriodBuilder_ == null) {
          tripReplacementPeriodBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod, com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod.Builder, com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriodOrBuilder>(
                  tripReplacementPeriod_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          tripReplacementPeriod_ = null;
        }
        return tripReplacementPeriodBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:transit_realtime.NyctFeedHeader)
    }
    
    static {
      defaultInstance = new NyctFeedHeader(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:transit_realtime.NyctFeedHeader)
  }
  
  public interface NyctTripDescriptorOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string train_id = 1;
    boolean hasTrainId();
    String getTrainId();
    
    // optional bool is_assigned = 2;
    boolean hasIsAssigned();
    boolean getIsAssigned();
    
    // optional .transit_realtime.NyctTripDescriptor.Direction direction = 3;
    boolean hasDirection();
    com.google.transit.realtime.GtfsRealtimeNYCT.NyctTripDescriptor.Direction getDirection();
  }
  public static final class NyctTripDescriptor extends
      com.google.protobuf.GeneratedMessage
      implements NyctTripDescriptorOrBuilder {
    // Use NyctTripDescriptor.newBuilder() to construct.
    private NyctTripDescriptor(Builder builder) {
      super(builder);
    }
    private NyctTripDescriptor(boolean noInit) {}
    
    private static final NyctTripDescriptor defaultInstance;
    public static NyctTripDescriptor getDefaultInstance() {
      return defaultInstance;
    }
    
    public NyctTripDescriptor getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.transit.realtime.GtfsRealtimeNYCT.internal_static_transit_realtime_NyctTripDescriptor_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.transit.realtime.GtfsRealtimeNYCT.internal_static_transit_realtime_NyctTripDescriptor_fieldAccessorTable;
    }
    
    public enum Direction
        implements com.google.protobuf.ProtocolMessageEnum {
      NORTH(0, 1),
      EAST(1, 2),
      SOUTH(2, 3),
      WEST(3, 4),
      ;
      
      public static final int NORTH_VALUE = 1;
      public static final int EAST_VALUE = 2;
      public static final int SOUTH_VALUE = 3;
      public static final int WEST_VALUE = 4;
      
      
      public final int getNumber() { return value; }
      
      public static Direction valueOf(int value) {
        switch (value) {
          case 1: return NORTH;
          case 2: return EAST;
          case 3: return SOUTH;
          case 4: return WEST;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Direction>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Direction>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Direction>() {
              public Direction findValueByNumber(int number) {
                return Direction.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.google.transit.realtime.GtfsRealtimeNYCT.NyctTripDescriptor.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Direction[] VALUES = {
        NORTH, EAST, SOUTH, WEST, 
      };
      
      public static Direction valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Direction(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:transit_realtime.NyctTripDescriptor.Direction)
    }
    
    private int bitField0_;
    // optional string train_id = 1;
    public static final int TRAIN_ID_FIELD_NUMBER = 1;
    private java.lang.Object trainId_;
    public boolean hasTrainId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getTrainId() {
      java.lang.Object ref = trainId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          trainId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTrainIdBytes() {
      java.lang.Object ref = trainId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        trainId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bool is_assigned = 2;
    public static final int IS_ASSIGNED_FIELD_NUMBER = 2;
    private boolean isAssigned_;
    public boolean hasIsAssigned() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public boolean getIsAssigned() {
      return isAssigned_;
    }
    
    // optional .transit_realtime.NyctTripDescriptor.Direction direction = 3;
    public static final int DIRECTION_FIELD_NUMBER = 3;
    private com.google.transit.realtime.GtfsRealtimeNYCT.NyctTripDescriptor.Direction direction_;
    public boolean hasDirection() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public com.google.transit.realtime.GtfsRealtimeNYCT.NyctTripDescriptor.Direction getDirection() {
      return direction_;
    }
    
    private void initFields() {
      trainId_ = "";
      isAssigned_ = false;
      direction_ = com.google.transit.realtime.GtfsRealtimeNYCT.NyctTripDescriptor.Direction.NORTH;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTrainIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, isAssigned_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, direction_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTrainIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, isAssigned_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, direction_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.google.transit.realtime.GtfsRealtimeNYCT.NyctTripDescriptor parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.transit.realtime.GtfsRealtimeNYCT.NyctTripDescriptor parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.transit.realtime.GtfsRealtimeNYCT.NyctTripDescriptor parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.transit.realtime.GtfsRealtimeNYCT.NyctTripDescriptor parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.transit.realtime.GtfsRealtimeNYCT.NyctTripDescriptor parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.transit.realtime.GtfsRealtimeNYCT.NyctTripDescriptor parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.google.transit.realtime.GtfsRealtimeNYCT.NyctTripDescriptor parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.transit.realtime.GtfsRealtimeNYCT.NyctTripDescriptor parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.transit.realtime.GtfsRealtimeNYCT.NyctTripDescriptor parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.transit.realtime.GtfsRealtimeNYCT.NyctTripDescriptor parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.transit.realtime.GtfsRealtimeNYCT.NyctTripDescriptor prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.google.transit.realtime.GtfsRealtimeNYCT.NyctTripDescriptorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.transit.realtime.GtfsRealtimeNYCT.internal_static_transit_realtime_NyctTripDescriptor_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.transit.realtime.GtfsRealtimeNYCT.internal_static_transit_realtime_NyctTripDescriptor_fieldAccessorTable;
      }
      
      // Construct using com.google.transit.realtime.GtfsRealtimeNYCT.NyctTripDescriptor.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        trainId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        isAssigned_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        direction_ = com.google.transit.realtime.GtfsRealtimeNYCT.NyctTripDescriptor.Direction.NORTH;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.transit.realtime.GtfsRealtimeNYCT.NyctTripDescriptor.getDescriptor();
      }
      
      public com.google.transit.realtime.GtfsRealtimeNYCT.NyctTripDescriptor getDefaultInstanceForType() {
        return com.google.transit.realtime.GtfsRealtimeNYCT.NyctTripDescriptor.getDefaultInstance();
      }
      
      public com.google.transit.realtime.GtfsRealtimeNYCT.NyctTripDescriptor build() {
        com.google.transit.realtime.GtfsRealtimeNYCT.NyctTripDescriptor result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.google.transit.realtime.GtfsRealtimeNYCT.NyctTripDescriptor buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.google.transit.realtime.GtfsRealtimeNYCT.NyctTripDescriptor result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.google.transit.realtime.GtfsRealtimeNYCT.NyctTripDescriptor buildPartial() {
        com.google.transit.realtime.GtfsRealtimeNYCT.NyctTripDescriptor result = new com.google.transit.realtime.GtfsRealtimeNYCT.NyctTripDescriptor(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.trainId_ = trainId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.isAssigned_ = isAssigned_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.direction_ = direction_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.transit.realtime.GtfsRealtimeNYCT.NyctTripDescriptor) {
          return mergeFrom((com.google.transit.realtime.GtfsRealtimeNYCT.NyctTripDescriptor)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.google.transit.realtime.GtfsRealtimeNYCT.NyctTripDescriptor other) {
        if (other == com.google.transit.realtime.GtfsRealtimeNYCT.NyctTripDescriptor.getDefaultInstance()) return this;
        if (other.hasTrainId()) {
          setTrainId(other.getTrainId());
        }
        if (other.hasIsAssigned()) {
          setIsAssigned(other.getIsAssigned());
        }
        if (other.hasDirection()) {
          setDirection(other.getDirection());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              trainId_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              isAssigned_ = input.readBool();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              com.google.transit.realtime.GtfsRealtimeNYCT.NyctTripDescriptor.Direction value = com.google.transit.realtime.GtfsRealtimeNYCT.NyctTripDescriptor.Direction.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                direction_ = value;
              }
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string train_id = 1;
      private java.lang.Object trainId_ = "";
      public boolean hasTrainId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getTrainId() {
        java.lang.Object ref = trainId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          trainId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTrainId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        trainId_ = value;
        onChanged();
        return this;
      }
      public Builder clearTrainId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        trainId_ = getDefaultInstance().getTrainId();
        onChanged();
        return this;
      }
      void setTrainId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        trainId_ = value;
        onChanged();
      }
      
      // optional bool is_assigned = 2;
      private boolean isAssigned_ ;
      public boolean hasIsAssigned() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public boolean getIsAssigned() {
        return isAssigned_;
      }
      public Builder setIsAssigned(boolean value) {
        bitField0_ |= 0x00000002;
        isAssigned_ = value;
        onChanged();
        return this;
      }
      public Builder clearIsAssigned() {
        bitField0_ = (bitField0_ & ~0x00000002);
        isAssigned_ = false;
        onChanged();
        return this;
      }
      
      // optional .transit_realtime.NyctTripDescriptor.Direction direction = 3;
      private com.google.transit.realtime.GtfsRealtimeNYCT.NyctTripDescriptor.Direction direction_ = com.google.transit.realtime.GtfsRealtimeNYCT.NyctTripDescriptor.Direction.NORTH;
      public boolean hasDirection() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public com.google.transit.realtime.GtfsRealtimeNYCT.NyctTripDescriptor.Direction getDirection() {
        return direction_;
      }
      public Builder setDirection(com.google.transit.realtime.GtfsRealtimeNYCT.NyctTripDescriptor.Direction value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        direction_ = value;
        onChanged();
        return this;
      }
      public Builder clearDirection() {
        bitField0_ = (bitField0_ & ~0x00000004);
        direction_ = com.google.transit.realtime.GtfsRealtimeNYCT.NyctTripDescriptor.Direction.NORTH;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:transit_realtime.NyctTripDescriptor)
    }
    
    static {
      defaultInstance = new NyctTripDescriptor(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:transit_realtime.NyctTripDescriptor)
  }
  
  public interface NyctStopTimeUpdateOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string scheduled_track = 1;
    boolean hasScheduledTrack();
    String getScheduledTrack();
    
    // optional string actual_track = 2;
    boolean hasActualTrack();
    String getActualTrack();
  }
  public static final class NyctStopTimeUpdate extends
      com.google.protobuf.GeneratedMessage
      implements NyctStopTimeUpdateOrBuilder {
    // Use NyctStopTimeUpdate.newBuilder() to construct.
    private NyctStopTimeUpdate(Builder builder) {
      super(builder);
    }
    private NyctStopTimeUpdate(boolean noInit) {}
    
    private static final NyctStopTimeUpdate defaultInstance;
    public static NyctStopTimeUpdate getDefaultInstance() {
      return defaultInstance;
    }
    
    public NyctStopTimeUpdate getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.transit.realtime.GtfsRealtimeNYCT.internal_static_transit_realtime_NyctStopTimeUpdate_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.transit.realtime.GtfsRealtimeNYCT.internal_static_transit_realtime_NyctStopTimeUpdate_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string scheduled_track = 1;
    public static final int SCHEDULED_TRACK_FIELD_NUMBER = 1;
    private java.lang.Object scheduledTrack_;
    public boolean hasScheduledTrack() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getScheduledTrack() {
      java.lang.Object ref = scheduledTrack_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          scheduledTrack_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getScheduledTrackBytes() {
      java.lang.Object ref = scheduledTrack_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        scheduledTrack_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string actual_track = 2;
    public static final int ACTUAL_TRACK_FIELD_NUMBER = 2;
    private java.lang.Object actualTrack_;
    public boolean hasActualTrack() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getActualTrack() {
      java.lang.Object ref = actualTrack_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          actualTrack_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getActualTrackBytes() {
      java.lang.Object ref = actualTrack_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        actualTrack_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      scheduledTrack_ = "";
      actualTrack_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getScheduledTrackBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getActualTrackBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getScheduledTrackBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getActualTrackBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.google.transit.realtime.GtfsRealtimeNYCT.NyctStopTimeUpdate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.transit.realtime.GtfsRealtimeNYCT.NyctStopTimeUpdate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.transit.realtime.GtfsRealtimeNYCT.NyctStopTimeUpdate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.transit.realtime.GtfsRealtimeNYCT.NyctStopTimeUpdate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.transit.realtime.GtfsRealtimeNYCT.NyctStopTimeUpdate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.transit.realtime.GtfsRealtimeNYCT.NyctStopTimeUpdate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.google.transit.realtime.GtfsRealtimeNYCT.NyctStopTimeUpdate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.transit.realtime.GtfsRealtimeNYCT.NyctStopTimeUpdate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.transit.realtime.GtfsRealtimeNYCT.NyctStopTimeUpdate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.transit.realtime.GtfsRealtimeNYCT.NyctStopTimeUpdate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.transit.realtime.GtfsRealtimeNYCT.NyctStopTimeUpdate prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.google.transit.realtime.GtfsRealtimeNYCT.NyctStopTimeUpdateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.transit.realtime.GtfsRealtimeNYCT.internal_static_transit_realtime_NyctStopTimeUpdate_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.transit.realtime.GtfsRealtimeNYCT.internal_static_transit_realtime_NyctStopTimeUpdate_fieldAccessorTable;
      }
      
      // Construct using com.google.transit.realtime.GtfsRealtimeNYCT.NyctStopTimeUpdate.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        scheduledTrack_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        actualTrack_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.transit.realtime.GtfsRealtimeNYCT.NyctStopTimeUpdate.getDescriptor();
      }
      
      public com.google.transit.realtime.GtfsRealtimeNYCT.NyctStopTimeUpdate getDefaultInstanceForType() {
        return com.google.transit.realtime.GtfsRealtimeNYCT.NyctStopTimeUpdate.getDefaultInstance();
      }
      
      public com.google.transit.realtime.GtfsRealtimeNYCT.NyctStopTimeUpdate build() {
        com.google.transit.realtime.GtfsRealtimeNYCT.NyctStopTimeUpdate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.google.transit.realtime.GtfsRealtimeNYCT.NyctStopTimeUpdate buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.google.transit.realtime.GtfsRealtimeNYCT.NyctStopTimeUpdate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.google.transit.realtime.GtfsRealtimeNYCT.NyctStopTimeUpdate buildPartial() {
        com.google.transit.realtime.GtfsRealtimeNYCT.NyctStopTimeUpdate result = new com.google.transit.realtime.GtfsRealtimeNYCT.NyctStopTimeUpdate(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.scheduledTrack_ = scheduledTrack_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.actualTrack_ = actualTrack_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.transit.realtime.GtfsRealtimeNYCT.NyctStopTimeUpdate) {
          return mergeFrom((com.google.transit.realtime.GtfsRealtimeNYCT.NyctStopTimeUpdate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.google.transit.realtime.GtfsRealtimeNYCT.NyctStopTimeUpdate other) {
        if (other == com.google.transit.realtime.GtfsRealtimeNYCT.NyctStopTimeUpdate.getDefaultInstance()) return this;
        if (other.hasScheduledTrack()) {
          setScheduledTrack(other.getScheduledTrack());
        }
        if (other.hasActualTrack()) {
          setActualTrack(other.getActualTrack());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              scheduledTrack_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              actualTrack_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string scheduled_track = 1;
      private java.lang.Object scheduledTrack_ = "";
      public boolean hasScheduledTrack() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getScheduledTrack() {
        java.lang.Object ref = scheduledTrack_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          scheduledTrack_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setScheduledTrack(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        scheduledTrack_ = value;
        onChanged();
        return this;
      }
      public Builder clearScheduledTrack() {
        bitField0_ = (bitField0_ & ~0x00000001);
        scheduledTrack_ = getDefaultInstance().getScheduledTrack();
        onChanged();
        return this;
      }
      void setScheduledTrack(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        scheduledTrack_ = value;
        onChanged();
      }
      
      // optional string actual_track = 2;
      private java.lang.Object actualTrack_ = "";
      public boolean hasActualTrack() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getActualTrack() {
        java.lang.Object ref = actualTrack_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          actualTrack_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setActualTrack(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        actualTrack_ = value;
        onChanged();
        return this;
      }
      public Builder clearActualTrack() {
        bitField0_ = (bitField0_ & ~0x00000002);
        actualTrack_ = getDefaultInstance().getActualTrack();
        onChanged();
        return this;
      }
      void setActualTrack(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        actualTrack_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:transit_realtime.NyctStopTimeUpdate)
    }
    
    static {
      defaultInstance = new NyctStopTimeUpdate(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:transit_realtime.NyctStopTimeUpdate)
  }
  
  public static final int NYCT_FEED_HEADER_FIELD_NUMBER = 1001;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.transit.realtime.GtfsRealtime.FeedHeader,
      com.google.transit.realtime.GtfsRealtimeNYCT.NyctFeedHeader> nyctFeedHeader = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.transit.realtime.GtfsRealtimeNYCT.NyctFeedHeader.class,
        com.google.transit.realtime.GtfsRealtimeNYCT.NyctFeedHeader.getDefaultInstance());
  public static final int NYCT_TRIP_DESCRIPTOR_FIELD_NUMBER = 1001;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.transit.realtime.GtfsRealtime.TripDescriptor,
      com.google.transit.realtime.GtfsRealtimeNYCT.NyctTripDescriptor> nyctTripDescriptor = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.transit.realtime.GtfsRealtimeNYCT.NyctTripDescriptor.class,
        com.google.transit.realtime.GtfsRealtimeNYCT.NyctTripDescriptor.getDefaultInstance());
  public static final int NYCT_STOP_TIME_UPDATE_FIELD_NUMBER = 1001;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.transit.realtime.GtfsRealtime.TripUpdate.StopTimeUpdate,
      com.google.transit.realtime.GtfsRealtimeNYCT.NyctStopTimeUpdate> nyctStopTimeUpdate = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.transit.realtime.GtfsRealtimeNYCT.NyctStopTimeUpdate.class,
        com.google.transit.realtime.GtfsRealtimeNYCT.NyctStopTimeUpdate.getDefaultInstance());
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_TripReplacementPeriod_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_transit_realtime_TripReplacementPeriod_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_NyctFeedHeader_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_transit_realtime_NyctFeedHeader_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_NyctTripDescriptor_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_transit_realtime_NyctTripDescriptor_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_NyctStopTimeUpdate_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_transit_realtime_NyctStopTimeUpdate_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n4com/google/transit/realtime/gtfs-realt" +
      "ime-NYCT.proto\022\020transit_realtime\032/com/go" +
      "ogle/transit/realtime/gtfs-realtime.prot" +
      "o\"b\n\025TripReplacementPeriod\022\020\n\010route_id\030\001" +
      " \001(\t\0227\n\022replacement_period\030\002 \001(\0132\033.trans" +
      "it_realtime.TimeRange\"w\n\016NyctFeedHeader\022" +
      "\033\n\023nyct_subway_version\030\001 \002(\t\022H\n\027trip_rep" +
      "lacement_period\030\002 \003(\0132\'.transit_realtime" +
      ".TripReplacementPeriod\"\265\001\n\022NyctTripDescr" +
      "iptor\022\020\n\010train_id\030\001 \001(\t\022\023\n\013is_assigned\030\002",
      " \001(\010\022A\n\tdirection\030\003 \001(\0162..transit_realti" +
      "me.NyctTripDescriptor.Direction\"5\n\tDirec" +
      "tion\022\t\n\005NORTH\020\001\022\010\n\004EAST\020\002\022\t\n\005SOUTH\020\003\022\010\n\004" +
      "WEST\020\004\"C\n\022NyctStopTimeUpdate\022\027\n\017schedule" +
      "d_track\030\001 \001(\t\022\024\n\014actual_track\030\002 \001(\t:Y\n\020n" +
      "yct_feed_header\022\034.transit_realtime.FeedH" +
      "eader\030\351\007 \001(\0132 .transit_realtime.NyctFeed" +
      "Header:e\n\024nyct_trip_descriptor\022 .transit" +
      "_realtime.TripDescriptor\030\351\007 \001(\0132$.transi" +
      "t_realtime.NyctTripDescriptor:q\n\025nyct_st",
      "op_time_update\022+.transit_realtime.TripUp" +
      "date.StopTimeUpdate\030\351\007 \001(\0132$.transit_rea" +
      "ltime.NyctStopTimeUpdateB\035\n\033com.google.t" +
      "ransit.realtime"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_transit_realtime_TripReplacementPeriod_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_transit_realtime_TripReplacementPeriod_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_transit_realtime_TripReplacementPeriod_descriptor,
              new java.lang.String[] { "RouteId", "ReplacementPeriod", },
              com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod.class,
              com.google.transit.realtime.GtfsRealtimeNYCT.TripReplacementPeriod.Builder.class);
          internal_static_transit_realtime_NyctFeedHeader_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_transit_realtime_NyctFeedHeader_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_transit_realtime_NyctFeedHeader_descriptor,
              new java.lang.String[] { "NyctSubwayVersion", "TripReplacementPeriod", },
              com.google.transit.realtime.GtfsRealtimeNYCT.NyctFeedHeader.class,
              com.google.transit.realtime.GtfsRealtimeNYCT.NyctFeedHeader.Builder.class);
          internal_static_transit_realtime_NyctTripDescriptor_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_transit_realtime_NyctTripDescriptor_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_transit_realtime_NyctTripDescriptor_descriptor,
              new java.lang.String[] { "TrainId", "IsAssigned", "Direction", },
              com.google.transit.realtime.GtfsRealtimeNYCT.NyctTripDescriptor.class,
              com.google.transit.realtime.GtfsRealtimeNYCT.NyctTripDescriptor.Builder.class);
          internal_static_transit_realtime_NyctStopTimeUpdate_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_transit_realtime_NyctStopTimeUpdate_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_transit_realtime_NyctStopTimeUpdate_descriptor,
              new java.lang.String[] { "ScheduledTrack", "ActualTrack", },
              com.google.transit.realtime.GtfsRealtimeNYCT.NyctStopTimeUpdate.class,
              com.google.transit.realtime.GtfsRealtimeNYCT.NyctStopTimeUpdate.Builder.class);
          nyctFeedHeader.internalInit(descriptor.getExtensions().get(0));
          nyctTripDescriptor.internalInit(descriptor.getExtensions().get(1));
          nyctStopTimeUpdate.internalInit(descriptor.getExtensions().get(2));
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.transit.realtime.GtfsRealtime.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
